### ISSUE TITLE
Empty locID's seem to disappear

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/documentation-wiki#102]
We have recently had cases where LocID's were created for data entry, but went unused for at least a few weeks due to other priorities. When we went back, the LocID's were missing. 10903282, 10903278, and 10903272 for example were created but disappeared. Is it possible to trace what happened to them from backups?  Is there an internal process where they are removed if not used up in time?  If that is the case, would it be possible to get an email telling us they are going bye bye, and an option to extend their life?

Thanks,

Chris Conroy

**Comment by Jegelewicz** [comment]
This is documented in the How-To - https://handbook.arctosdb.org/how_to/How-to-Create-a-Locality.html#creating-a-locality

Closing.
