### ISSUE TITLE
It would be great if there was a form on Arctos that would generate eml files needed for the ipt

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#108]
All of UTEP eml files need to be updated too and this is something I requested a long time ago. We need to collect the data required by the ipt in Arctos and then have the ability to generate the eml file to send to VertNet. @acdoll I think it would help if we started with an eml mock-up where we put the fields currently in the "manage collection" form into the eml, then we see what is missing from Arctos "manage collection" and see if we can add those fields there to complete a "push to eml" function. Care to take that on?

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/1787#issuecomment-437414707_

**Comment by acdoll** [comment]
@dustymc the EML generator does not input the license selected on the manage collection page. We had CC-BY-NC selected for all of our collections (except DMNS:Inv, which I just changed), but the data from EML generator includes the CC0 license. John D. noticed the CC0 license on GBIF (also at VertNet); is that coming from this generator or is that a residual from some old EML we sent them in the past?

**Comment by dustymc** [comment]
@acdoll see https://github.com/ArctosDB/arctos/issues/2566

That's hard-coded. There's a giant issue somewhere (maybe even this one), but in any case the idea that collections need to change that before passing the EML on to vertnet (which passes it on to GBIF et al) was at best poorly communicated. I believe the old behavior was that vertnet had that hard-coded; the EML generator added more flexibility, not less, but perhaps in the most cryptic way possible.

The critical issue has been hanging around for several months now. I'm very open to the idea that I should drop everything else and just implement it as I understand it. Please advise!!

**Comment by campmlc** [comment]
I think this should be high priority as we are going to need to test the PG
publication to VertNet anyway. Best to get it right the first time.
But please help with the current critical issues first . . . at least mine!
:)

**Comment by Jegelewicz** [comment]
>     field mapping
> 
> https://github.com/ArctosDB/DDL/blob/master/flat/ipt_view.sql

![image](https://user-images.githubusercontent.com/5725767/136980877-a88b29b0-dfed-4aa1-89ee-394330facfdd.png)

**Comment by dustymc** [comment]
https://github.com/ArctosDB/PG_DDL/blob/master/shared_data/dwc_occurrence.sql

**Comment by Jegelewicz** [comment]
This is all documented in https://handbook.arctosdb.org/how_to/How-to-Publish-to-GBIF.html but it does seem like it would be good to make the mapping more available so I added a link. Closing.
