### ISSUE TITLE
In list view specimen results - move 'identified by' next to sci name

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/documentation-wiki#109]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

I previously had a field that indicated who did the id in my optional fields to display in the list view of specimen record results, and this field was next to the sciname/ID but now it's gone. I thus went into the add/remove fields dialog and selected 'identified by' but when this field displays it's on the far right side of the display so I have to scroll to the far right to see it (and it really belongs next to the sci name since it's the person who assigned that name).

**Describe the solution you'd like**

Move that field to the left so it's adjacent to sci name

**Describe alternatives you've considered**

**Additional context**

**Priority**
I would like to have this resolved by date: ___30 oct 2018____

**Comment by dustymc** [comment]
<img width="177" alt="screen shot 2018-10-26 at 1 17 43 pm" src="https://user-images.githubusercontent.com/5720791/47590645-cfe77200-d921-11e8-8d6d-797631adb814.png">

<img width="225" alt="screen shot 2018-10-26 at 1 18 12 pm" src="https://user-images.githubusercontent.com/5720791/47590650-d5dd5300-d921-11e8-8eb7-2b53b79e47a6.png">

<img width="304" alt="screen shot 2018-10-26 at 1 19 12 pm" src="https://user-images.githubusercontent.com/5720791/47590661-daa20700-d921-11e8-83a6-33f7e6e25361.png">

**Comment by Jegelewicz** [comment]
I think this will be changed by the new search form. Closing.
