### ISSUE TITLE
Access to Institutional Operator List

### ISSUE THREAD

**Issue by srobson4** [ArctosDB/documentation-wiki#110]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I would like to be able to access a list of operators and assigned roles just for my institution.  I need to regularly audit and maintain user access for our collection (students come and go and I need to be sure to revoke when they leave).  I found 'all user statistics" page, but its static and I can't sort it by reported institution.

**Describe the solution you'd like**
Is it possible to create sortable headers or filters on the all user statistics page?  Or create a list of operators for people who have manage collection roles?

**Describe alternatives you've considered**
Scrolling through the very very long list in all user statistics or copy-and-pasting then sorting in a spreadsheet.

**Additional context**
n/a
**Priority**
I would like to have this resolved by date:  31 Oct 2018

**Comment by Jegelewicz** [comment]
Done here - https://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html#1-managing-and-reviewing-operator-roles-and-permissions closing
