### ISSUE TITLE
Georeferencing Assistance

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#112]
Does anyone have a written protocol for recording georeferences in Arctos? I am increasingly unable to wrap my mind around the best way to record the original collection as per the collector's notes and then supplement that with a georeference completed at a later date by someone else (who did not collect the specimen on the date they did the georeference, but somehow that is still a "collection" event?).

See also ArctosDB/arctos#843 ArctosDB/arctos#739 ArctosDB/arctos#1705 ArctosDB/arctos#1109 ArctosDB/arctos#752

**Comment by acoconis** [comment]
Hi! I'm a bit confused by this. Have there been any further discussions of this? When adding a specimen event to describe my georeferencing details, I am having trouble with filling out the fields. I have looked at the documentation for specimen events, but the specimen event types don't seem to match what I am looking for. Any guidance would be much appreciated! I apologize if I am missing something obvious.

**Comment by Jegelewicz** [comment]
@acoconis which fields are giving you trouble and what event type are you looking for?

**Comment by acoconis** [comment]
> @acoconis which fields are giving you trouble and what event type are you looking for?

@Jegelewicz mainly just the specimen event type.

So when I edit a locality, at the bottom of the locality page, I see I can add a specimen/event. If I am only georeferencing from a legacy specimen, none of the event types seem to fit. And I assume the collecting event is the one the specimen is in... correct?

Thanks for the help!

**Comment by Jegelewicz** [comment]
> If I am only georeferencing from a legacy specimen, none of the event types seem to fit.

I'm not sure that I understand, but georeferencing should reflect whatever the original event was. So if you are adding coordinates to the data from a collecting event, then the event type would be "collection" and so on. A georeference is just a new interpretation of the legacy data. So you are now saying "this collection happened at these coordinates" instead of just "this collection happened at the place described on the label". The determiner for the georeference should be whoever calculated the coordinates.

Does that help?

**Comment by acoconis** [comment]
Ah. I see. Okay, yes this makes sense. Thank you!

**Comment by Jegelewicz** [comment]
I am unsure what needs documenting here. Closing.
