### ISSUE TITLE
Turn off Coordinates in search results?

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/documentation-wiki#116]
Is it possible to remove the decimal latitude, decimal longitude, and coordinate error columns in the search results view using the "add or remove data columns" tool? This information is NEVER useful for the UAM:EH or UAM:Art search results - we care about the specific locality not the precise coordinates. If I could hide those columns I could show other information that is much more important for my users.

**Comment by AJLinn** [comment]
> I enabled columnSelectable so you should be able to right-click on the header table row and turn things off (next release, hopefully tonight). I think that works via cookies so it should persist in your browser, but it will NOT follow your user around like the "normal" customization stuff.


SWEET! Thanks - this is so much better...

**Comment by Jegelewicz** [comment]
I am closing this - it will be covered in documentation on the new search form.
