### ISSUE TITLE
add depth units

### ISSUE THREAD

**Issue by KatherineLAnderson** [ArctosDB/documentation-wiki#117]
Are the depth min and max fields an appropriate place to note pit depth for paleontological collections? They seem to be used primarily for ocean/water depth based on the units available but doesn't state it is strictly for that use in the documentation. Can cm and inches be added as units?

**Comment by Jegelewicz** [comment]
Me too, but eventually you may need km, mm, and even miles. However, I suggest we keep the units consistent with other unit fields: cm, ft, cm and so on.

**Comment by Jegelewicz** [comment]
Documentation updated - https://handbook.arctosdb.org/documentation/locality.html#depths
closing
