### ISSUE TITLE
character warning, documentation/idea request

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/documentation-wiki#120]
This has come up a few times recently, so I'm bringing it up here. I'm not sure it is something we can fix, other than through documentation and perhaps software recommendations, but I'm certainly open for ideas.

Various software apps mangle non-ASCII characters in various ways, usually by converting from one non-UTF format to another. We end up with � (and several other variations of characters that ultimately meant "I don't know what to do with this character") in various fields. There's no reversing this process - thousands of characters all get squished into � (although it's usually just Spanish accents). 

There are multiple ways of convincing various applications to print something that looks like a UTF character. Arctos generally displays data in HTML, and HTML has lots of ways of displaying UTF characters from non-UTF data. Occasionally � gets "fixed" into the HTML-encoded ASCII string (`&ntilde;` for example), which looks a lot like ñ in HTML applications. However, it's not searchable by ñ (only by the string `&ntilde;`), and it looks like what it is - `&ntilde;` - in non-HTML applications (like the Arctos reporter).

Here's one from the collecting event logs - as HTML

UAM@ARCTOS> select verbatim_locality from collecting_event where collecting_event_id=11245736;

VERBATIM_LOCALITY
------------------------------------------------------------------------------------------------------------------------
Mexico, Coahuila, Mpio Casta&ntilde;os, On Hwy 57, 8 Mi. N Cuesta La Muralla

and, hopefully, as UTF

```
UAM@ARCTOS> select verbatim_locality from collecting_event where collecting_event_id=11245736;

VERBATIM_LOCALITY
------------------------------------------------------------------------------------------------------------------------
Mexico, Coahuila, Mpio Casta&ntilde;os, On Hwy 57, 8 Mi. N Cuesta La Muralla
```

and an image, just in case...

<img width="702" alt="screen shot 2018-10-05 at 7 56 53 am" src="https://user-images.githubusercontent.com/5720791/46542832-44277c00-c874-11e8-9ad3-b9ea04b0f629.png">

I'm not really sure where to go from here, other than documenting this somewhere.

**Comment by Jegelewicz** [comment]
I think we have this covered with https://handbook.arctosdb.org/documentation/understanding-errors.html#error-row-for-relation-table-violates-check-constraint-ck_column_noprint Closing
