### ISSUE TITLE
DISCUSS: User Management

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/documentation-wiki#123]
Documentation: https://handbook.arctosdb.org/documentation/sharing-data-and-resources.html

Code: https://github.com/ArctosDB/documentation-wiki/edit/gh-pages/_documentation/sharing-data-and-resources.markdown

- [ ] @KyndallH suggests how to video
- [ ] http://handbook.arctosdb.org/documentation/sharing-data-and-resources.html needs some gaps filled in. I added a blurb, but I think a user's perspective is needed.
- [ ] There are a lot of empty cells on the 'read this' table; we need more documentation, particularly video.
- [ ] It would be useful if documentation occasionally mentioned what NOT to do - "if THAT, then editing THIS will alter 70,000 specimens and turn into a huge mess, so instead I'll...."
- [x] There's some documentation at http://handbook.arctosdb.org/documentation/users.html, but it should be beefed up. If I wanted to "hack" Arctos I'd probably start by just asking someone to give me access....added this to the documentation index - probably no one was seeing it!
- [x] Add link to this issue
- [x] Add navigation

```
What steps will reproduce the problem?

1. Let admin users grant anyone their rights

- What is the expected output? 

Users awesomifying collections after having carefully read the documentation.

- What do you see instead?

Users apparently hurling fingers in the general direction of their keyboard.

Please use labels and text to provide additional information.

There are dangerous forms in shared nodes (eg, containers) and there are users 
who create extremely unexpected error messages from these forms. I suggest the 
AC should take a more active role in monitoring access to shared nodes, or 
limit grant access, or provide a test before allowing access (Gordon's best 
idea ever!), or SOMETHING. It seems only a matter of time before someone who 
should perhaps not yet have admin access finds a way to cause significant 
damage to an unrelated collection. 
```

Original issue reported on code.google.com by `dust...@gmail.com` on 18 Aug 2015 at 3:05

**Comment by Jegelewicz** [comment]
I think the written documentation is fairly solid. I also added the User documentation as reading for new collections as part of the Create an Arctos Team step in data migration. The video tutorial label is still here - although I am a bit unclear what that would entail.
