### ISSUE TITLE
Geology - Add Biostratigraphy

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/documentation-wiki#124]
**Table**
[Geology Attributes] (http://arctos.database.museum/info/ctDocumentation.cfm?table=CTGEOLOGY_ATTRIBUTE)

**Value**
Biostratigraphy

**Definition**
A body of rock strata that is defined or characterized on the basis of its contained fossils - Salvador, A. (ed.) 1994. _International stratigraphic guide_. Boulder, CO: Geological Society of America.

**Context**
Another category needs to be created in geology for biostratigraphic and biochronologic units. The difference between these two is equivalent to the difference between chronostratigraphy and geochronology. A **biozone** (biostratigraphy) is rocks containing certain index taxa and a **biochron** (biochronology) is the time represented by that taxon range. The units used for some taxa may be biozones (ex. Ammonites); the units for other taxa may be biochrons (ex. North American Land Mammal Ages), but biochrons are theoretically always based on biozones. Some biozones and biochrons may have subintervals. A question to consider is can we group these by the kind of index taxon used (ex. North American Land Mammals vs. Western Interior Seaway Ammonites)?

A useful reference for background information: [Late Cretaceous and Cenozoic Mammals of North America: Biostratigraphy and Geochronology](https://books.google.com/books?hl=en&lr=&id=fNuXaC_LcgwC&oi=fnd&pg=PR5&dq=Late+Cretaceous+and+Cenozoic+Mammals+of+North+America:+Biostratigraphy+and+Geochronology&ots=Rv7S_6xmEs&sig=pTjsKuAAIsby0rkWsHa0B7lwSiM#v=onepage&q&f=false) especially the definitions starting on page xi.

**Comment by Jegelewicz** [comment]
Calling this one done - https://handbook.arctosdb.org/documentation/geology.html#biostratigraphy
