### ISSUE TITLE
Add encumbrance action to mask all locality information except higher geography

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#130]
"mask coordinates" does not equal "mask locality" even though that's what the documentation claims.

["NOTE: A locality encumbrance (i.e. “Mask Coordinates”) will mask data below the County level only. If a higher degree of discretion is necessary, an encumbrance must be created for the entire record."
](http://handbook.arctosdb.org/how_to/How-to-Create-an-Encumbrance.html)

I placed the ["mask coordinates" encumbrance](http://arctos.database.museum/Encumbrances.cfm?action=listEncumbrances&encumbrance_id=10000419) on [the single record in NMMNH:Paleo](http://arctos.database.museum/guid/NMMNH:Paleo:1) and the only data this hides is the coordinates. We need to be able to hide everything below County (and possibly ALL locality info - @Nicole-Ridgwell-NMMNHS can add to this). Just masking the coordinates is not enough when attempting to hide localities from poachers....

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> Is there any merit to the idea of flagging localities/events/specimen-events/something as 'private' so that you can have full control of this?

I like that idea. A previous database I worked in just had a checkbox you could click to hide a specific record.

**Comment by Jegelewicz** [comment]
Write documentation on current usage of geology attribute. Add blurb to "encumbrance" documentation.

**Comment by Jegelewicz** [comment]
https://handbook.arctosdb.org/how_to/How-to-Encumber-Locality.html

I am calling this one done.
