### ISSUE TITLE
Locality Attributes

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/documentation-wiki#133]
So, I'm trying to envision how our data, particularly localities, will migrate into Arctos. From what I can tell, the only way to bulkload localities is to attach the locality data to the specimen data and bulkload it with the specimens. This would be very difficult for us because of the way our data is structured, the limitations of Access, and the quantity of records. I had hoped we could bulkload the localities and specimens separately, using LOCALITY_NAME to link the two. Is there a way to do this?

**Comment by Jegelewicz** [comment]
>     ovverride on the "Wikipedia only"
> 
> I'd at least whine - I can (and do) use that to find funky data. Without, I have no way to catch "Florida, Some Quad in Utah" (and those data have a way of showing up...).

Could we broaden it to be urls? I guess people could fake those, but are we those people? (I hope not!)

I am totally OK with putting all of the stuff discussed above in Locality Attributes, but we are going to need to set up some controlled vocabularies for some of them. If we are going to treat all this stuff as a locality attribute, can we get those up and running quickly? I have less than 40 weeks to get NMMNH data migrated (80,000 records) so we need to make a decision and get going.

**Comment by dustymc** [comment]
> load it.

Nope...

ORA-01400: cannot insert NULL into ("UAM"."LOCALITY"."GEOG_AUTH_REC_ID")
ORA-06512: at line 3


Elapsed: 00:00:00.23
UAM@ARCTOS> select higher_geog from temp_nmmnh_loc where higher_geog not in (select higher_geog from GEOG_AUTH_REC);

HIGHER_GEOG
------------------------------------------------------------------------------------------------------------------------
North America, United States, New Mexico, Sandoval County, Bernalillo 15 minute
North America, United States, New Mexico, Guadalupe County, Ima NW 7.5 minute
North America, United States, New Mexico, Sandoval County, Five Lakes Canyon NE 7.5 minut
North America, United States, New Mexico, Sandoval County, Five Lakes Canyon NE 7.5 minut
North America, United States, New Mexico, Rio Arriba County, Five Lakes Canyon NE 7.5 minut

5 rows selected.



And please rename GEOG_AUTH_REC_ID to higher_geog.

**Comment by Jegelewicz** [comment]
Code table updated. Thanks!

**Comment by Jegelewicz** [comment]
[Documentation](http://handbook.arctosdb.org/documentation/geology.html) has been updated. @dustymc @Nicole-Ridgwell-NMMNHS @dperriguey @mbprondzinski please review and let me know if anything needs changing.

Still need to write How to Add geology Attributes

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I would specify that, for now, we are including some non-geology locality attributes under "geology attributes" but that this is a temporary workaround.

**Comment by dperriguey** [comment]
What does create two catalog record events mean in the Encumbering Locality link? Do you mean collecting event or specimen event? Am I creating a whole new catalog record? If collecting event, how do I do that? I used "Clone Event (new event under this locality)" with no luck, and the documentation for how to do this is also poor on the Collecting Event page.

**Comment by Jegelewicz** [comment]
> What does create two catalog record events mean in the Encumbering Locality link? Do you mean collecting event or specimen event?

Both

> Am I creating a whole new catalog record?

No - two events for one catalog record

> I used "Clone Event (new event under this locality)" with no luck, and the documentation for how to do this is also poor on the Collecting Event page.

That would be a way to make it easier. I haven't looked at that documentation, and I really can't right at this moment. @dperriguey if you will give me access to your collection, I could do one of these for you so that you can see how it looks.

**Comment by dperriguey** [comment]
I'm happy to give you access, but that would leave me in the same place really. I see the example for NMMNHS. I just need to know how to make multiple events. I've accidentally done it before through bulk loading, like the documentation says.

**Comment by Jegelewicz** [comment]
You can't see the whole thing because you don't have access to NMMNH collections. Once I do one for you it will be more clear.

**Comment by dperriguey** [comment]
Ok, you have access now under UNM: ES

**Comment by Jegelewicz** [comment]
Which catalog number should I use?

**Comment by dperriguey** [comment]
2378

**Comment by Jegelewicz** [comment]
[This](https://github.com/ArctosDB/arctos/issues/2353#issuecomment-548980706) might help - I'm working on yours now.

**Comment by Jegelewicz** [comment]
Step one - clone the named locality

> remove everything from the cloned locality except higher geography including the locality nickname. Add back any geology. Save it.


2 - Add a Collecting Event (button at bottom of locality edit page)

> Verbatim locality = Contact collection for details
> Verbatim date = same as research event
> Began date  = same as research event
> Ended date = same as research event
> No coordinates here

SAVE

3 - Return to your record. Edit Location
Add an event (scroll down)

Complete same as the research event

Select "Pick new event" button

Search specific locality "New Mexico, Cibola County (no specific locality)"
Select "Find Matches"
Select "Use This" next the appropriate locality (there could be more than one as geologies and dates proliferate...)
Select Create Specimen Event

The generic public locality will not have coordinates if you created it, but you can get them added more quickly by asking @mkoo to put it at the top of the list.

See [2378](https://arctos.database.museum/guid/UNM:ES:2378) now. Try it when logged in and not.

Let me know how crappy my instructions are and if you can PLEASE help me write some documentation!

**Comment by dperriguey** [comment]
I get some weird error when I delete coordinate stuff. I'm clearing out everything in the coordinates box or if I leave that box alone when I try to save my edits to the new locality. 

![image](https://user-images.githubusercontent.com/32556913/70072782-e47e4b00-15b4-11ea-9d63-4f7a9ce739b1.png)

**Comment by Jegelewicz** [comment]
@dperriguey give me the locality number so @dustymc can check it out.

**Comment by dperriguey** [comment]
It's ok. I figured out the problem. I'll add it to your instructions here in a bit when I finish.

**Comment by dperriguey** [comment]
Step one - clone the named locality

remove everything from the cloned locality except higher geography and specific locality. Add back any geology. Save it.

2 - Add a Collecting Event (button at bottom of locality edit page)

Verbatim locality = Contact collection for details
Verbatim date = same as research event
Began date = same as research event
Ended date = same as research event
No coordinates here

SAVE

3 - Return to your record. Edit Location
Add an event (scroll down to the Add Specimen/Event box)

Complete same as the research event

Select "Pick new event" button

Search Locality ID using the new cloned locality
Select "Find Matches"
Select "Use This" next the appropriate locality (there could be more than one as geologies and dates proliferate...)
Select Create Specimen Event

**Comment by dperriguey** [comment]
I have a problem with how access:private functions. iDigBio does not use higher geography to create coordinates on their map. I would like to be able to use the new coordinates I make in the cloned locality. See http://arctos.database.museum/guid/UNM:ES:2379 @dustymc @Jegelewicz 
I'm sure these are duplicates and not what we want (localities at the county level), so I probably need to use these differently (like check for duplicates first?). 

We're trying to be able to show the spatial coverage of our collection without giving the exact coordinates of the original event in accordance with the law. Is it possible to make the access:private attribute work only for the locality it is used on?

**Comment by Jegelewicz** [comment]
> I have a problem with how access:private functions. iDigBio does not use higher geography to create coordinates on their map. I would like to be able to use the new coordinates I make in the cloned locality. See http://arctos.database.museum/guid/UNM:ES:2379 @dustymc @Jegelewicz
> I'm sure these are duplicates and not what we want (localities at the county level), so I probably need to use these differently (like check for duplicates first?).
> 
> We're trying to be able to show the spatial coverage of our collection without giving the exact coordinates of the original event in accordance with the law. Is it possible to make the access:private attribute work only for the locality it is used on?

These can have wkt/coordinates added please see #2353 and if you will send a list of the ones you need WKT added to @mkoo hopefully it can get done quicker.

**Comment by Jegelewicz** [comment]
> I would specify that, for now, we are including some non-geology locality attributes under "geology attributes" but that this is a temporary workaround.

See NOTE

**Comment by Jegelewicz** [comment]
Calling this done - https://handbook.arctosdb.org/documentation/geology.html
