### ISSUE TITLE
Deleting a Specimen Record

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/documentation-wiki#137]
I discovered a duplicate record that was recently added, but I am unable to get rid of it.  The Arctos "How to" Delete a Specimen Record is not up to date.  There is no "Expiration Event" category in the Create an Encumbrance page.  Also, I cannot delete it from the Accession without deleting the entire Accession!  What exactly do I need to do to delete a record???

**Comment by campmlc** [comment]
Hi Mary Beth,
1) First you need to create an encumbrance with the action mask record. Put
" duplicate records for deletion" in remarks, so you know what to use this
encumbrance for in the future. Don't worry about expiration date, although
you should put five years from now, which is the longest you can do.

2) Search on the record. From the top tool bar on the specimen page, select
encumbrances.

3) search for the encumbrance you just created with your name as agent and
the remarks field above.

4) Click to "Add items below to this encumbrance".

5) Once the record is added, go back to the encumbrance. Once you are in
the encumbrance page, you should see the number of records in the
encumbrance. When you are ready to delete those records, choose "delete all
records in this encumbrance" and confirm at the prompt. The records will be
deleted.

**Comment by mbprondzinski** [comment]
Merci beaucoup!  That worked…  Thanks!

**Comment by Jegelewicz** [comment]
Does [this](http://handbook.arctosdb.org/how_to/How-to-Delete-Specimen-Records.html) not cover that adequately? If not, can one of you please update the How-To?

**Comment by mbprondzinski** [comment]
The instructions are not up-to-date.  There is no "Expiration Event" field.  I tried the "restrict usage" for the "Encumbrance Action" and got an error message.  I was not able to create an Encumbrance per the instructions.

**Comment by campmlc** [comment]
Documentation updated. @mbprondzinski  please confirm.

**Comment by Jegelewicz** [comment]
Thanks @campmlc!
