### ISSUE TITLE
How to find documentation files for editing

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/documentation-wiki#138]
Trying to search on the documentation for how to edit documentation is frustrating in Github because the relevant file name is:
How-to-Contribute-Content-to-Arctos-Handbook.markdown
Therefore, searches for "edit-documentation" or "edit-handbook" yield no results. I suggest renaming this file and associated hyperlinks with:
How-to-Contribute-and-Edit-Content-to-Arctos-Handbook-and-Documentation.markdown
which will pull up the correct file for the above searches. We shouldn't have to know that "Contribute-Content" are the magic words to edit the handbook or the documentation.
@mkoo can we make this change and redirect the links?

**Comment by dustymc** [comment]
>and redirect the links

As far as I know, the answer to that is "no" which should be seen as a moderately compelling reason not to change things.

>search

I feel dirty for even half-heartedly defending the github search thing, but it does search content. This works, for example

<img width="250" alt="Screen Shot 2019-12-02 at 5 58 26 PM" src="https://user-images.githubusercontent.com/5720791/70013718-64f96900-152d-11ea-9bee-fff25e68f728.png">


Adding something about "edit handbook" somewhere in the text should make that work as a search term.

I think the dashes will break about any string-match search (and there are quite a few unicode characters that look like dashes, just to complicate things).

**Comment by campmlc** [comment]
I get no results for "edit do" in the file finder. The words documentation and edit are in the correct document, but do not pull up for me on a search.
I get no results if I use file finder and don't use dashes. Am I searching in the wrong place? 
The only search that yields the correct file is "handbook". 
It shouldn't be this hard to find out how to edit the handbook or the documentation . . . 

A search on just "documentation" yields the first result of https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_documentation/documentation.markdown which looks very old and incomplete, and which tells viewers to go to a link for a Handy How To Page that 404s.
Can we make this go away? In the meantime, I'm adding a redirect to the right file.

**Comment by dustymc** [comment]
Aha, maybe! You're trying to search the code tree, right? I was looking at the rendered document.

I don't use the inline editor so I won't be much help there. A central point of git is that it allows anyone to use whatever tools they're comfortable with. If you're writing 'how to edit' documentation I think it would only apply to a thin slice of users (and is likely redundant with any decent editor, which would have its own documentation).

**Comment by campmlc** [comment]
Yes, as that is what the editing documentation directs us to, and as far as I can tell I don't see any other obvious place to search once I click on arctos documentation-wiki?
I think we need to make searching on how to edit and add to documentation very, very obvious. Any ideas if we can't change the titles of existing files?

**Comment by Jegelewicz** [comment]
First, all the git hub stuff is summarized on the resources page:

![image](https://user-images.githubusercontent.com/5725767/70065799-e6421180-15a8-11ea-9a95-958526838dc9.png)

But, can we make the search look at the entire document instead of just the document titles?

**Comment by Jegelewicz** [comment]
I think this has been covered by adding a link to direct edit each page.
