### ISSUE TITLE
General permits for Gifts and Purchases

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/documentation-wiki#146]
So I started looking a bit at the required permits for accessions. After talking to a few of my cultural collection colleagues, we're wondering if it's possible to create two "generic" collecting permits that we could add to our accessions that are either gifts or purchases. We could probably do one for transfers also.

Generic Collecting Permit for all items **donated**

permit number: "not assigned"
Permit type:  collect
Issued To: University of Alaska Museum of the North
Issued By: unknown
Contact: NULL
Issued Date: NULL
Expires Date: NULL
Remarks: Deed of Gift

Second generic collecting permit for **Purchases,** with all the others the same
Remarks: Bill of Sale

If we're expected to create a unique permit for every one of my nearly 2000 accessions, I'm not doing it - I'll just keep clicking the "I don't want to enter the info now" button every time I update an accession record. I already have the info in my files and it's a duplicate of the info in the accession record.

Thoughts? I think it would be a valuable thing for everyone who has gifts and purchases.

**Comment by Jegelewicz** [comment]
@dustymc I added stuff from the Permit documentation to the table browser. Maybe for "field-level" documentation, the table browser should be our single source of truth? Can we expose that for everyone to view or just pull it into documentation?

https://arctos.database.museum/tblbrowse.cfm?tbl=permit

connected to

https://handbook.arctosdb.org/documentation/permits.html

BUT that doesn't provide a place for the description of "permit" itself. Can we do that somewhere?

I know you brought this up somewhere else, but instead of looking for it, I thought I would just work on some of this. Let me know if it is crazy.

**Comment by dustymc** [comment]
>table browser should be our single source of truth

I strongly support the idea of SOME single source of truth.

I don't think anything can be more connected than this so it's always seemed like the natural choice, but I'm sure that's tinted by my geeky outlook. @mkoo mentioned something that might be a better wrapper on the same sort of data/structure but I can't find it at the moment. (Whatever that was might have what's requested the below, probably worth discussing plug-in tools before we do much to the homegrown.)

>connected to

I'm not sure what that means, probably dependent on the "user," but I can put up APIs/endpoints/whatever to provide those data in various forms.

>expose that for everyone 

I think it is, if not I think it can be. MAYBE reality (probably wearing a Russian IP address if the weekend's activity is predictive...) will change my mind at some point, but even then most of it should be public and all of it can probably always be available for even entry-level "us."

>provide a place for the description of "permit" itself.

I don't seem to have any persistent structure for that, but it could be added. BUT, adding something could also be misleading. Tables are the sums of their columns and constraints, I'm not sure anything could be added that would be very useful - and not potentially misleading - to anyone who cares much about table structure and so might find themselves in this form. I don't think there's a "no" anywhere in there, but there's also about zero chance that any human is ever going to see all of the possibilities of a table in some way that can be strung into sentences and I think that should be (somehow) considered.

That's also probably not true for the big weird "composite" tables - https://arctos.database.museum/tblbrowse.cfm?tbl=bulkloader and https://arctos.database.museum/tblbrowse.cfm?tbl=flat and such - and those are where it might be most useful too.

**Comment by dustymc** [comment]
docs updated
