### ISSUE TITLE
entering dates for wild caught animals that were in the lab for months before euth

### ISSUE THREAD

**Issue by acoconis** [ArctosDB/documentation-wiki#147]
What date should be entered for specimen event and collecting event if the animal was wild caught but then in the lab on diet trials for months before euthanization? Thanks!

**Comment by campmlc** [comment]
The collecting event date should be the date of removal from the wild, and
the attribute verbatim preservation date should be the date of euthanasia.
Collecting event remarks and attribute remarks can be used to provide
additional information. You can also choose to use "captive" as a specimen
event; we are discussing moving this to an attribute, which could then have
a date of determination and remarks. However, until this happens a captive
event may remove the coordinates from mapping.

**Comment by campmlc** [comment]
"captive" is currently "collection source". If we move this to an
attribute, then a record could have both "wild-caught" and "captive"
attributes.

**Comment by dustymc** [comment]
>move this to an attribute,

We are discussing supplementing. The event will still somehow convey ~'this isn't natural,' the attribute would expand on that.
