### ISSUE TITLE
Need to update System Details Page of arctos.db.org

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#151]
https://arctosdb.org/about/details/system/

Remove Oracle/ColdFusion stuff and change to Lucee PostgreSQL

**Comment by mkoo** [comment]
Did not remove all mentions of Oracle but made it clear we are now in Postgresql. Updated language about CFML->HTML environment.

Also updated FAQ page which has brief answers about database and interface languages, too.
