### ISSUE TITLE
New error in Bulkloader - can we make it easier to address the problem?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#160]
I bulkloaded some stuff, fixed some things after validation, re-validated and I get 

![image](https://user-images.githubusercontent.com/5725767/96934030-c5afce00-147e-11eb-95fd-8bcedb1fb7e1.png)

An error occurred while processing this page!
Message: ERROR: new row for relation "bulkloader" violates check constraint "ck_bl_vbtm_loc_noprint"
Detail:
Check the Arctos Handbook for more information on errors.

This message has been logged as F0B63034-70DB-4173-A203FA58B5C677B0 Please contact us with any information that might help us to resolve this problem. For best results, include the error and a detail description of how it came to occur in the Issue. 

First problem - it is convoluted path to get back to fixing things in the grid. (Either hit the back button from the error page - I don't who would just do that - or return to the bulkloader main page, select validate, then select Cleanup from the bottom of the list - a long path around.)

Second problem - once I get there, I don't know which row(s) have the non-printing character in verbatim locality....

Any chance this can act like everything else and just put an error in the status of the offending row?

**Comment by dustymc** [comment]
Filemaker! I haven't seen a vertical tab in so long!

**Comment by Jegelewicz** [comment]
above solution added to How To - closing
