### ISSUE TITLE
Misspelled Taxon Name

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/documentation-wiki#161]
I just realized that I misspelled a taxon name I (re)added after the data loss last April. It is spelled Pecopteris fontanei, but should be Pecopteris fontainei. I attempted to fix the misspelling, but I am unable to fix it, because I used the term in two other records. Is there a way to update the taxon name?

Although it says it is probably_not_valid, a google search suggests it is valid and I have a Mazon Creek book published in 2006 that lists the name as valid.

**Comment by Jegelewicz** [comment]
Add the correct spelling. Change the identifications to the correct spelling. Delete the incorrect spelling OR quarantine it and create mispelling of relationship to the correct spelling.

**Comment by cefilipek** [comment]
Thanks!
