### ISSUE TITLE
Georeference Source vs Georeference Protocol

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/documentation-wiki#168]
I would like clarification on how to use Georeference Source vs Georeference Protocol when coordinates were determined after the fact for legacy data, using GeoLocate. Should both fields be "GeoLocate"? 
Also, we do not have a remarks field for georeferencing information. Should any remarks from the person who did the georeferencing go under specimen event remarks? This should be clear in the documentation.

**Comment by tucotuco** [comment]
For what it is worth, GEOLocate does not publish a protocol, so using that value wouldn't strictly be correct. I would imply, "whatever it is that GEOLocate does."
