### ISSUE TITLE
Cloning in data entry question

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/documentation-wiki#172]
I entered a single data record (after much sturm und drang) saved it and then cloned it to use again. IIt appears to have replaced the previous record because both records are not in the bulk loader, only the "cloned" record. I can find no information on "cloning records" so I guess I am the first person to have tried this?!

**Comment by campmlc** [comment]
Did you mark the original record to load? Could it already be in Arctos?

**Comment by mbprondzinski** [comment]
Hi Marielle, this was from 2019 and I have no recollection of what it was about!  You can close it out.
________________________________

**Comment by campmlc** [comment]
OK!
