### ISSUE TITLE
Geology attribute: private

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#174]
With regard to https://github.com/ArctosDB/documentation-wiki/issues/133 I woke up last night thinking about the DwC output for aggregators. Will the private (access) geology attribute also prevent those localities from appearing in the information shared to aggregators? We need to make sure it will.

**Comment by gradyjt** [comment]
Hey @Jegelewicz! I wanted to first brag for a second and report that I successfully figured out how to encumber a locality for a record by creating two collecting events (one private, one open access with minimal info) thanks to your documentation in the handbook, woop woop! I was trying to find an appropriate place (hopefully here) to mention that the only snag I had was that in the "how-to" it says to control access through "geology attributes" but it appears they're now called "locality attributes". I wasn't sure if I should bring that to your attention or if I could help update that documentation in the how-to for "encumber a locality" and the one for "add geology attributes to a locality"? Thanks!

**Comment by Jegelewicz** [comment]
@gradyjt Woot woot! Thanks for that - I will update!

**Comment by Jegelewicz** [comment]
Updates complete - hope I caught it all.
