### ISSUE TITLE
Catalog Item Type Change

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#183]
Also needs documentation and [announcement in Arctos Newsletter](https://github.com/ArctosDB/newsletter/issues/53).

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/2432#issuecomment-776847573_

**Comment by Jegelewicz** [comment]
Added to [How To Manage a Collection](https://handbook.arctosdb.org/how_to/How-to-Manage-a-Collection-in-Arctos.html#default-cataloged-item-type).

**Comment by Jegelewicz** [comment]
Dusty added to [Documentation](https://handbook.arctosdb.org/documentation/catalog.html#cataloged-item-type)

**Comment by dustymc** [comment]
I didn't do it! This has always been there, we just haven't made much use of it.

**Comment by Jegelewicz** [comment]
I thought it needed changing - does it?

**Comment by Jegelewicz** [comment]
Added to [Bulkloader Field Documentation](https://handbook.arctosdb.org/documentation/bulkloader.html#fields)

**Comment by Jegelewicz** [comment]
I think that covers the documentation. @dustymc if you can think of anywhere else that needs an update, let me know.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Once we get the code table updated, I assume updating our default to fossil specimen in Manage Collection will only effect new specimens and to update the old I'll have to do some sort of batch update?

**Comment by dustymc** [comment]
Yep, you can send me a list of GUIDs/values or there could be a bulk-changer if that looks like it'll be a common thing.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Ok, here is our list of GUIDs that need to be changed to Fossil Specimen:
[FossilSpecimenGuids.zip](https://github.com/ArctosDB/documentation-wiki/files/6030224/FossilSpecimenGuids.zip)

**Comment by dustymc** [comment]
"fossil specimen" right? If we do this again please just include the value.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
> "fossil specimen" right? If we do this again please just include the value.

Yes, sorry about that

**Comment by dustymc** [comment]
And a CSV header please!

I did this

```
create table temp_nmmmmmmnhcitype  as select * from temp_cache.temp_dlm_uptbl ;
alter table temp_nmmmmmmnhcitype add cid bigint;

update temp_nmmmmmmnhcitype set cid=(select collection_object_id from flat where flat.guid=temp_nmmmmmmnhcitype.guid);

alter table temp_nmmmmmmnhcitype add cataloged_item_type varchar;

update temp_nmmmmmmnhcitype set cataloged_item_type='fossil specimen';

UPDATE cataloged_item
SET cataloged_item_type = temp_nmmmmmmnhcitype.cataloged_item_type
FROM temp_nmmmmmmnhcitype
WHERE temp_nmmmmmmnhcitype.cid = cataloged_item.collection_object_id;
UPDATE 79351


```

It'll take a while to clear the cache.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Thanks!
