### ISSUE TITLE
Collector names with no additional infomormation

### ISSUE THREAD

**Issue by acoconis** [ArctosDB/documentation-wiki#184]
We have a lot of collections obtained from old research labs where only the name, and sometimes just the first initial and last name (ie. J. Smith), have remained with the record as far as collector goes. Some of these names may be students but we don't have any other information about them. This being said, what do you suggest we do as far as entering these records into Arctos? I just felt like adding a bunch of random names wasn't the best idea.

**Comment by Jegelewicz** [comment]
I think that all of this is documented in [Agent](https://handbook.arctosdb.org/documentation/agent.html)
