### ISSUE TITLE
New Tutorial - how to use new batch tools format

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/documentation-wiki#191]
I had the data prepared for our last office hours to demonstrate how to use the new batch tools format. Other topics were requested during the office hours, so I went ahead and just recorded a how-to. The video has been added to the Arctos tutorials google folder and I've entered it in the tutorial sign-up.

**Comment by Jegelewicz** [comment]
@ebraker

**Comment by ebraker** [comment]
Awesome! Thanks so much @Nicole-Ridgwell-NMMNHS. I'll post this tomorrow.

**Comment by ewommack** [comment]
Yeah! Thank you @Nicole-Ridgwell-NMMNHS !

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Your welcome!
