### ISSUE TITLE
Duplicate Indexes

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#2]
There are two index pages for the documentation Wiki.  This will likely lead to confusion.  I suggest we either delete the "Index" off the Wiki home page and replace it with a link the the Index page or delete the index page and make the home page the index.  The two indexes are:

https://github.com/ArctosDB/documentation-wiki/wiki

and

https://github.com/ArctosDB/documentation-wiki/wiki/Index-to-Arctos-Documentation-and-How-To-Guides

**Comment by mkoo** [comment]
Addressed with new site design (see #7). Closing
