### ISSUE TITLE
Best Practices - choosing a GUID prefix

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#206]
We have discussed documenting "best practices" and I'd like to propose we make this a separate part of our handbook. How Tos show you how to do things in Arctos, Best Practices offer advice for the most efficient way to record information in Arctos to increase discoverability and make work easier. My first stab at this is best practice for selecting a GUID Prefix. Since we have had a couple of collections decide on something different after they had started cataloging, I'd like to offer an explanation of what the GUID Prefix is and how to make a decision on one for an incoming collection in an effort to help new collections choose wisely. I have a document started at https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_best_practices/GUID.markdown which I will work on over the next few weeks. I'll ask for input once I have a draft.

**Comment by dustymc** [comment]
I definitely like the idea of a dedicated place for documenting "best practices," but I'm not so sure that picking a guid_prefix is one - part of that seems like pure documentation, "thou shalt" land, and the rest (the value) is mostly arbitrary, so I'm not sure there's a "best" way to get at that either.

https://handbook.arctosdb.org/documentation/catalog.html#guid-prefix

>collections decide on something different 

Our MOU/administration is obviously broken - https://github.com/ArctosDB/internal/issues/92

**Comment by dustymc** [comment]
>Choosing an Institutional Acronym and Collection Name (GUID Prefix)

FYI those are three completely unrelated things.

**Comment by Jegelewicz** [comment]
> the value) is mostly arbitrary

and I hope this will help make it less so. This can be a difficult decision for new collections to make, especially if they haven't published data before.

> FYI those are three completely unrelated things.

Sigh. Not for my purposes.

MSB = Institutional Acronym
Mamm = Collection Name
MSB:Mamm = GUID Prefix

I also plan to discuss

collection code = Mamm (from the [code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde))

I want to make reading the document part of deciding what gets put into the MOU so that we are sure we have had a clear conversation about what they are selecting and why we recommend what we do.

**Comment by dustymc** [comment]
GP really is arbitrary! I'd think understanding that rather than being lead to believe there's some sort of dependency would make the decision easier, especially if they happen to have multiple "Mamm" collections (vascular plants and other plantish stuff is common) or weird "institutional" organization (eg MSB/DRG) or something of the sort.

I'm not sure what you're calling "Collection Name."

**Comment by Jegelewicz** [comment]
> "Collection Name."

The stuff after the colon - which is what has traditionally gotten us into trouble (starting out using the collection code "ES" only to realize a year later that they would rather have "Paleo". I hope to make it clear that there is no dependency, but that there can be ways to pick something more useful than UTEP:colls

**Comment by Jegelewicz** [comment]
@dustymc 'splain me something...

How are we using [Institution Acronym](https://handbook.arctosdb.org/documentation/catalog.html#institution-acronym) in Arctos? (What does it DO?) and what does it DO that the stuff before the colon in [GUID Prefix](https://handbook.arctosdb.org/documentation/catalog.html#guid-prefix) doesn't?

**Comment by dustymc** [comment]
>What does it DO?

Nuthin.

>what does it DO that the stuff before the colon in GUID Prefix doesn't?

Provides one "UAM" despite three "UAM:Herb" collections.

**Comment by Jegelewicz** [comment]
OK, so maybe not "Nuthin"?

I assume that although the Arkansas Herbarium uses STAR in it's GUID Prefix, it's institutional Acronym is still ACBC? Which makes me think the portals page should sort first by institutional acronym, then by GUID prefix....

![image](https://user-images.githubusercontent.com/5725767/125661637-2588389d-be1c-424b-8adb-f49c65404ad7.png)

![image](https://user-images.githubusercontent.com/5725767/125661548-c86de443-1433-4c4a-948a-c0aa878e26b0.png)

**Comment by dustymc** [comment]
> not "Nuthin"

I think it does something for people, not machines.

>assume

Yea I think the parens-bit.

>sort

Whatever, should be easy to change.

https://github.com/ArctosDB/arctos/issues/1662 is also involved.

**Comment by campmlc** [comment]
Yes, ASUMZ (Zoology) and STAR (herbarium) are the original collection codes
combined into the overall ACBC

**Comment by Jegelewicz** [comment]
> I think it does something for people, not machines.

I know something it DOES in Arctos - it becomes one with a barcode series?

![image](https://user-images.githubusercontent.com/5725767/125667975-5c8fcf2b-14f4-4721-9a6e-c4fe0fc654e9.png)

I guess I am wondering what the hell. WHY do we make this thing SOOOOOO important (it is greyed out in Manage Collection) but it doesn't DO anything important? It has to be doing SOMETHING important or we wouldn't care if people changed it.

![image](https://user-images.githubusercontent.com/5725767/125668923-48679380-5bfb-4d69-a7f5-30fdceb04ca4.png)

I understand what Collection Type does - limits vocabularies and what GUID prefix does - creates unique catalog identifiers in Arctos, but the other three are mysteries to me.

If the Alabama Museum of Natural History changes it's name to Alabama Museum of Nature and Science, what will that break?

**Comment by Jegelewicz** [comment]
And WHY don't all of the Albama collections include (ALMNH)?

![image](https://user-images.githubusercontent.com/5725767/125669428-5723b717-6667-48c2-9e98-af5d618391df.png)

**Comment by Jegelewicz** [comment]
Somewhere along the way it was decided to leave the acronym off of the Institution name?

![image](https://user-images.githubusercontent.com/5725767/125669636-730bed4b-6b3d-4533-8b97-b9c74475f1f6.png)

**Comment by dustymc** [comment]
>barcode

Ah - correct. (Ish - that's a "weak key" at best, but yes that idea is there.)

>greyed out 

Some of that was probably written pre-guid-prefix.

>mysteries

Evolution is a stupid process! I'd definitely go for backing up and figuring out how to make real keys to containers (or if we need that at all) and what all the junk in collection is supposed to do and etc.


>changes...break?

Potentially something in DWC-land, nothing in Arctos.

>WHY don't all 

Same as ArctosDB/arctos#1662  - we can, therefore we do.

This thing:

<img width="612" alt="Screen Shot 2021-07-14 at 11 04 06 AM" src="https://user-images.githubusercontent.com/5720791/125670857-5abcf8cb-22ab-4c26-b01d-69db0a3d9ca2.png">

also feed off of this mess.

https://github.com/ArctosDB/arctos/issues/3027 might need something in collection.

>understand what Collection Type does 

https://github.com/ArctosDB/arctos/issues/3452 might change that.

**Comment by Jegelewicz** [comment]
>     changes...break?
> 
> Potentially something in DWC-land, nothing in Arctos.

It is part of how this is built.

![image](https://user-images.githubusercontent.com/5725767/125672984-fb502bf3-f1ef-4750-b765-2b8b16ca7d3a.png)

..but if the title of a dataset changes, that shouldn't change the whole thing? Is that some sort of key? I certainly hope not....

Maybe @dbloom can tell us?

WHY is everything  a cluster?  Why don't all of these datasets have the same Institution Acronym?

![image](https://user-images.githubusercontent.com/5725767/125673967-8ada2a76-e677-4de4-b016-1aa21ca64382.png)

https://www.gbif.org/dataset/search?publishing_org=ac1a4340-812c-11de-86fe-b8a03c50a862

@lin-fred @Nicole-Ridgwell-NMMNHS FYI

**Comment by lin-fred** [comment]
Good catch. The official name is New Mexico Museum of Natural History & Science (NMMNH&S)
Does this have to be edited in GBIF or in Arctos, or both?

Although, to clarify, our GUID is NMMNH

**Comment by Jegelewicz** [comment]
@lin-fred that depends - here is how the information appears in Arctos for that Inv collection:

![image](https://user-images.githubusercontent.com/5725767/125678507-d4f331ad-babf-4676-9644-7075b8ba0942.png)

I am guessing that the EML for that was made by hand instead of with the [EML generator in Arctos](https://arctos.database.museum/info/ipt.cfm).

However, the EML generator will title ALL of the NMMNHS collections as follows:

New Mexico Museum of Natural History and Science (NMMNHS) **Collection** (Arctos) where **Collection** would be replaced with whatever is in Collection in Manage Collection

![image](https://user-images.githubusercontent.com/5725767/125679149-2c866f2e-556c-41b3-82d6-b7ec9be3a085.png)

If all of the "and"s should be replaced with & we might end up breaking stuff?

I cannot believe I wasn't more on top of this when the collections were first created!

**Comment by lin-fred** [comment]
I seem to recall we decided it need to be "and" instead of "&" to not break stuff. Although it just gets confusing with our GUID being NMMNH, then our institutions being NMMNHS and our official tittle being NMMNH&S. Oh well, luckily it's all close enough and not a major name change.. Let me know if I need to do anything?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
@lin-fred I'm not sure what acronym bio has been using, but for the paleo specimens the acronym is NMMNH. I'm surprised I didn't notice this when I was reviewing Manage Collection for GBIF upload. @Jegelewicz How do we go about fixing this?

**Comment by lin-fred** [comment]
@Nicole-Ridgwell-NMMNHS So what do we want to be listed as the name for the museum? New Mexico Museum of Natural History and Science (NMMNH) ?

**Comment by Jegelewicz** [comment]
The whole "acronym", collection code, collection type, GUID Prefix problem put me here. These are all poorly understood and I hope I can remedy that going forward, but here is the deal.

All of the NMMNH collections have Institution Acronym = NMMNHS

![image](https://user-images.githubusercontent.com/5725767/125685055-529496ab-b58a-4fa5-aab6-3e2485b91ac3.png)

They also ALL use "NMMNH" before the colon in their GUID Prefix

![image](https://user-images.githubusercontent.com/5725767/125685172-54deb29e-94c4-40c4-bf12-e61d3ca6477e.png)

And they all have New Mexico Museum of Natural History and Science (NMMNHS) in Institution
![image](https://user-images.githubusercontent.com/5725767/125685327-162f418e-3a95-4f43-a418-976ce0c253e7.png)

BUT some of these collections have something different in their registration at GBIF. I don't understand how this happened, because we have the EML generator that should have made them all consistent. Maybe some were created prior to that tool being around? If you want my opinion - I wouldn't "change" anything in Arctos. I think that new EML files should be generated for the inconsistent collections (Inv, Herb, Mamm and Herp), then we will probably need either @mkoo or @dbloom to help us get that in the right hands.

**Comment by lin-fred** [comment]
>Maybe some were created prior to that tool being around?

Only the Mammal one was uploaded a long time ago by Dave Hafner, all of the others are new, so it's possible that maybe some were duplicated from that original Mammal one and some used the EML. I remember @dbloom was having some issues with getting the EML to work. I do recall some used the EML, while some didn't during the original creation.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I would like NMMNH paleo to be changed to NMMNH in both the acronym field and institution name. That has been our standardized institutional acronym for specimen citation since the museum was founded and otherwise it will be confusing to researchers about which to use.

Clearly it would be helpful to have definitions for these? I knew next to nothing about Arctos when we were setting this up and I didn't really have a clear idea about how they would be used.

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS The Institutional Acronym isn't published anywhere - it is used internally to manage barcode series and to be able to get all collections from a single institution. There really is no need to change it.

As for the name - see https://github.com/ArctosDB/documentation-wiki/issues/206#issuecomment-880092143

**Comment by lin-fred** [comment]
@Nicole-Ridgwell-NMMNHS @Jegelewicz referencing the "Institution" New Mexico Museum of Natural History and Science (NMMNHS). Should it be NMMNH? As that is what people would need to search on? Not NMMNHS?

Also, should our barcodes be NMMNH instead of NMMNHS? Important to discuss for sure.

**Comment by Jegelewicz** [comment]
The NMMNHS is not "in" the barcodes. It is used to relate your collections to the barcode series. So, your institutional barcode is NMMNHS
![image](https://user-images.githubusercontent.com/5725767/125690886-1764580b-a41d-417c-b9fa-58c644006735.png)

your barcodes all start with NMMNH
![image](https://user-images.githubusercontent.com/5725767/125691003-5979c3e9-3b37-4a41-b4c7-1665512c8b10.png)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
>and to be able to get all collections from a single institution.

What does that mean?

I guess if the acronym is entirely internal I'm not as concerned about it.

**Comment by Jegelewicz** [comment]
> What does that mean?

Ability to find all collections with the same Institutional Acronym. Arkansas (ACBC) has collections with GUID Prefix that start with STAR and with ASUMZ, but they all have Institutional Acronym of ACBC which creates a path for finding all their stuff (hopefully).
