### ISSUE TITLE
How to Start as a New Collection in Arctos need updated

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#207]
GrBio is not a thing.

**Comment by dustymc** [comment]
And the GBIF replacement still doesn't DO anything of which I'm aware. Why are we making new collections jump that hurdle?

**Comment by Jegelewicz** [comment]
> Why are we making new collections jump that hurdle?

To be fair - it does help to discover that they already have data published under one of the GBIF Publisher acronyms....and if they go ahead and get registered, when it DOES do something they won;t have to play catch up.

**Comment by Jegelewicz** [comment]
All references to GRBIO removed.
