### ISSUE TITLE
Change text on Manage Collection Page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#209]
![image](https://user-images.githubusercontent.com/5725767/125682111-c3afdb0e-4f3a-4830-8a7b-ba46ec17af6e.png)

I suggest we change "Collection Type" to "Collection Code" so that we are providing direct information about where this comes from, which is the [Collection Code code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde).

**Comment by Jegelewicz** [comment]
@dustymc I've worked on it a bit more. I think a little table for each of these might be helpful and I can add as I work on stuff. What do you think?

https://handbook.arctosdb.org/documentation/catalog.html#collection-code

**Comment by dustymc** [comment]
https://handbook.arctosdb.org/documentation/catalog.html#collection-type - note that changing stuff there changes URLs, which sometimes breaks documentation. 

https://github.com/ArctosDB/arctos/issues/1075

The table is hawt, but also I might be the worst possible person to evaluate that sort of thing.

And "editable" is "we have SQL, and we can use it if we absolutely must" - it's easier to change than guid_prefix, MAYBE that's useful information for a new collection, maybe it's just confusing, IDK.

You should remove Gordon's "Collection . Institution_Acronym VARCHAR2(20) null" blurbs while you're in there (or at least change it to the correct datatype, if there's some value in keeping it).

**Comment by Jegelewicz** [comment]
Commenting in Markdown = [//]: # (See https://github.com/ArctosDB/documentation-wiki/issues/209)

but that only works for an entire line.

See also https://stackoverflow.com/questions/37364722/how-do-i-add-inline-comments-in-github-flavored-markdown

Which says this should work  but apparently not?

> The table is hawt

That's good?

> "editable" is "we have SQL, and we can use it if we absolutely must"

Yeah, but I'm going to use this to mean "editable by Arctos operator with appropriate access".

> You should remove Gordon's "Collection . Institution_Acronym VARCHAR2(20) null" blurbs while you're in there (or at least change it to the correct datatype, if there's some value in keeping it).

OMG - I have always assumed those were use and had some kind of meaning for you. I sorta understand them, but I feel pretty sure everyone else ignores them.

As for the little table - anything else that should be there?

**Comment by dustymc** [comment]
>but that only works

.... in a few of the bajillion parsers, generally....

Yes good. I don't think anything's missing but I'm still me so....

No I've got SQL and a table browser, and I think we all know how I feel about doing the same thing in multiple places (and here's why!), it ain't my fault.

**Comment by Jegelewicz** [comment]
> https://handbook.arctosdb.org/documentation/catalog.html#collection-type - note that changing stuff there changes URLs, which sometimes breaks documentation.

Solution: use HTML

![image](https://user-images.githubusercontent.com/5725767/125832427-ba4a7be5-47f8-4d1e-ad65-9e715e976552.png)

get this

![image](https://user-images.githubusercontent.com/5725767/125832350-d256237b-bb8d-4f12-b7bc-11070da01263.png)

**Comment by Jegelewicz** [comment]
Why is the handbook written in Markdown as opposed to HTML? @dustymc @mkoo

**Comment by dustymc** [comment]
The decision to convert was made at the Sevillita meeting.

Markdown is a very simple language, about anyone can contribute to the handbook.

Github has markdown-->magic-->html functionality.

**Comment by Jegelewicz** [comment]
But as far as I can tell, very few are editing? And that magic doesn't do some of the things we need.

For instance, the markdown for the "stable" links does not translate, but the HTML works great....

**Comment by mkoo** [comment]
You can use html in markdown. Markdown is basically easier (in theory) HTML
shortcodes. So everything in *.md gets converted to HTML

Do whatever you prefer.

**Comment by mkoo** [comment]
your screenshots are pointing to CSS issue which is slightly different

**Comment by dustymc** [comment]
>markdown for the "stable" links does not translate,

You are arbitrarily changing things (or finishing up an earlier arbitrary change, or something). The HTML is just adding an explicitly-named anchor (which no longer quite agrees with the text). My take-home would be (and always has been) that we need to coordinate changes.

**Comment by Jegelewicz** [comment]
> The HTML is just adding an explicitly-named anchor (which no longer quite agrees with the text).

Which means I can change the text without breaking links...No?
