### ISSUE TITLE
How To index page

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/documentation-wiki#21]
currently lists How To pages in alphabetic order based on file name dynamically. Keep as is?

**Comment by tigerhawkvok** [comment]
Index pages general sorting  from old discussions:

![image](https://cloud.githubusercontent.com/assets/165937/17946617/eec29afa-69fd-11e6-9e21-1c28df72f26b.png)

**Comment by tigerhawkvok** [comment]
Changed to sort by title as per #23
