### ISSUE TITLE
Handbook Expansion Improvements

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#214]
Currently the Handbook Home Page looks like this:

![image](https://user-images.githubusercontent.com/5725767/126215600-c00bffcd-0381-4ac3-a47c-331af25908a5.png)

I propose that we add a section to the handbook called "Best Practices". @dustymc suggests this should be between Documentation (technical specs) and How To (Steps to complete a task in Arctos). An example of this would be the [Documentation for Loan Type](https://handbook.arctosdb.org/documentation/loans.html#type), the [Best Practice for Selecting a Loan Type](https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_best_practices/Loan_Type.markdown) and [How To Create a New Loan](https://handbook.arctosdb.org/how_to/How-to-Create-a-New-Loan.html).

**Comment by mkoo** [comment]
ok I can set up a test home page -- should we add a 5th icon or replace the last one with the Arctos link with the new one?

**Comment by Jegelewicz** [comment]
> should we add a 5th icon or replace the last one with the Arctos link with the new one?

Seems like there's space - add a new one?

**Comment by mkoo** [comment]
I was thinking the same!

**Comment by mkoo** [comment]
ok to make live?
https://handbook.arctosdb.org/index_new.html

Index page is simple, auto-listing all pages in the directory.
Love the "loan tree" graphic!
MK

**Comment by Jegelewicz** [comment]
I'm good with it! @ccicero  was mostly responsible for the graphic...I just tweaked it a bit and PUBLISHED it!
