### ISSUE TITLE
Video Bear for video tutorials?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#223]
@ebraker I wonder if you might like to design a "video bear" that we could use to highlight video tutorials in our How Tos? Sorta like the Pro bear we have for tips..

![image](https://user-images.githubusercontent.com/5725767/127063719-b6cf10ec-803d-43f4-9a35-a602823e97e0.png)

**Comment by ebraker** [comment]
What about this?
![video_bear](https://user-images.githubusercontent.com/11336485/127195933-3b25b50e-ed36-4b8c-8a1c-569ca2ab4bd6.png)

**Comment by Jegelewicz** [comment]
nice! Can you make a small one - like 60x60 pixels and save it [here](https://github.com/ArctosDB/documentation-wiki/tree/gh-pages/tutorial_images) as "Bear play"?

**Comment by ebraker** [comment]
@Jegelewicz Done!

**Comment by Jegelewicz** [comment]
What do you think?

https://handbook.arctosdb.org/how_to/How-to-Create-Agents.html

**Comment by ebraker** [comment]
Looks fab!

**Comment by Jegelewicz** [comment]
Yay! Thank you!!!
