### ISSUE TITLE
Best Practice update - Creating meaningful Agents

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#224]
Please complete the form to the best of your ability. This will help us find the document and complete the update.

ArctosDB.org url: https://handbook.arctosdb.org/best_practices/Agents.html

Github code: https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_best_practices/Agents.markdown

The following need to be added/changed/deleted 

 - [ ] Could use some review by others

The following could use some more work

 - [x] Need note on preferred name
 - [ ] Need note on aka

**No need to complete below this point - these are reminders for the person working on the update**

 - [x] Add a link to this issue at the top of the document (use "Add to current update request" as the text for the link)
 - [x] Add a link to this issue to the community discussion section of this document (use "Github Issue #X" as the text for the link)

When the above are complete:

 - [ ] Comment the link created at the top of the document. (use  [//]: # before the link so it will not display on the page, but will remain in the code)

Notify the Arctos Community of the update:

 - [ ] Social Media
 - [ ] Google Group
 - [ ] Newsletter

**Comment by Jegelewicz** [comment]
@dustymc I am working on this and as I do also trying to add descriptions in the table browser - https://arctos.database.museum/tblbrowse.cfm?tbl=agent

Please let me know if any of these look crazy.

|column name|description|data type|null?|length|code table|
|-----------|-----------|---------|-----|------|----------|
|agent_id|Agent table primary key.|bigint|NO|||
|agent_type|Select from values in the <a href="http://arctos.database.museum/info/ctDocumentation.cfm?table=CTAGENT_TYPE" target="blank">agent type code table</a>|character varying|NO|30|[ctagent_type](http://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_type)|
|preferred_agent_name|Unique text string describing the agent.|character varying|NO|255||
|created_by_agent_id|agent_id of the Arctos user who created the agent.|bigint|NO|||
|created_date|Date the agent was created.|timestamp without time zone|NO|||
|agent_remarks|Non-standardized information that might be helpful to other users in disambiguating agents. Never use remarks for data which can be linked or formalized elsewhere. HTML can be used to increase readability.|character varying|YES|4000||

**Comment by Jegelewicz** [comment]
Also - is there any way to expose this table for Arctos operators to see (not edit)? I think it might be useful and rather than copy pasting it and then having it be wrong wherever it was pasted the next day it could be a living dictionary of Arctos data tables.  Just wishing...

**Comment by dustymc** [comment]
Consensus is to document tables and concepts in ``https://handbook.arctosdb.org/documentation/``, authority-intention in code table metadata, and authority values in code tables.
