### ISSUE TITLE
How To update - Convert TRS to Coordinates

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#232]
Please complete the form to the best of your ability. This will help us find the document and complete the update.

How To: https://handbook.arctosdb.org/how_to/Convert_TRS_to_Lat-Long_Using_GeoLocate.html

In Github: https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_how_to/Convert_TRS_to_Lat-Long_Using_GeoLocate.markdown

> I'm using your instructions on How To Convert Township/Range/Section data to Latitude/Longitude Coordinates Using GeoLocate from the Arctos Handbook. You say to include the country and state. I've been including the county as well. Isn't it possible that there might be two locations in the same state with different meridians and baselines but the same TRS numbers?

The following could use some more work

 - [x] Include the country and county in instructions. 
 - [x] Update screenshots to include county

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS could you provide new screenshots that include the county?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
![image](https://user-images.githubusercontent.com/47402809/130133893-61146f6d-1b67-437f-8be9-609c67200589.png)
![image](https://user-images.githubusercontent.com/47402809/130134079-f702f280-6bef-4fc2-9a22-102f6e3de731.png)
![image](https://user-images.githubusercontent.com/47402809/130134260-23c62df0-731c-4dc8-8129-a960d49140a2.png)
![image](https://user-images.githubusercontent.com/47402809/130134447-f98b57ff-2fce-43c2-a750-e3dea5b4ae85.png)
![image](https://user-images.githubusercontent.com/47402809/130134606-4ac7f57f-0599-482b-b4e0-07ad5d52c998.png)
![image](https://user-images.githubusercontent.com/47402809/130134859-4591d6c6-8ea3-46c6-b56f-d588b3ad4871.png)

**Comment by Jegelewicz** [comment]
Thanks!!!

**Comment by Jegelewicz** [comment]
Added to repo and document updated.
