### ISSUE TITLE
Best Practice - TACC Media Allocation

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#244]
Need advice on creating directory structures in the Arctos Project Allocation at TACC.

**Comment by dustymc** [comment]
Some version of 

```
/{institution}/collection_or_whatever/some_project/maybe_other_stuff/{yyyy_mm_dd}/
```

Institution (for "our" accounting) and the dailies (for everyone's sanity) are the important parts, the "project folders" in the middle are entirely optional.

**Comment by Jegelewicz** [comment]
[Draft started](https://handbook.arctosdb.org/best_practices/TACC_allocation.html) - please give feedback or edit directly!

**Comment by dustymc** [comment]
>    Once loaded, files may only be removed by a TACC user with write permissions to the folder in which the files is stored.


I don't think that's true. The file *should* be owned by, and only "writable" (includes deletion) by, the creating user. Other users being able to write to the dir should not change anything.

Perhaps our expectation of immutability should be stressed more - NOBODY should be even thinking about changing anything here, even if they can. "Access" seems to be a central, or at least recurring, concern, which makes me think we are completely failing to communicate the intent of this service. It should all be forever-resources, and changing that is a pretty big deal - minimally any changes will need pushed to the Arctos Media records (and failing that will make me think there's stuff that isn't used and needs deleted, and there's the potential for all kinds of crazy from there.)

>byt

typo

Something about naming conventions would be useful - https://handbook.arctosdb.org/documentation/media.html#media-uri

Maybe the idea that I'm not going to be able to script giant piles of files should be emphasized - eg I don't even SORTA have the resources it would take to do ANYTHING with something like https://web.corral.tacc.utexas.edu/MVZ/eggs/photos/, if we do figure out post-processing at some point that will probably not be eligible. (Yay daily directories....)

It's not going to be possible to list out everything that's going to prevent some usage at some future date, but that's the intent behind those things.

"Small batches of things named using unix conventions" is kinda in the vicinity of safe, maybe.

**Comment by Jegelewicz** [comment]
>     Once loaded, files may only be removed by a TACC user with write permissions to the folder in which the files is stored.
> 
> I don't think that's true. The file should be owned by, and only "writable" (includes deletion) by, the creating user. Other users being able to write to the dir should not change anything.

Changed to: Once loaded, files may only be removed by the TACC user who uploaded them.

> Perhaps our expectation of immutability should be stressed more - NOBODY should be even thinking about changing anything here, even if they can. "Access" seems to be a central, or at least recurring, concern, which makes me think we are completely failing to communicate the intent of this service. It should all be forever-resources, and changing that is a pretty big deal - minimally any changes will need pushed to the Arctos Media records (and failing that will make me think there's stuff that isn't used and needs deleted, and there's the potential for all kinds of crazy from there.)

Added to summary, but it also stated at the top under cautions: Files stored in the Arctos Project Allocation at TACC should be considered to be **archived in perpetuity**. The intent of this service is to provide "forever-resources" and changing that is a pretty big deal!

> Something about naming conventions would be useful - https://handbook.arctosdb.org/documentation/media.html#media-uri

Added: Follow standard file naming practices such as those in [Arctos Media: Media URI Documentation](documentation/media.html#media-uri). Specifically, name files using ony A-Z, a-z, 0-9, and _ 

> Maybe the idea that I'm not going to be able to script giant piles of files should be emphasized - eg I don't even SORTA have the resources it would take to do ANYTHING with something like https://web.corral.tacc.utexas.edu/MVZ/eggs/photos/, if we do figure out post-processing at some point that will probably not be eligible. (Yay daily directories....)

That is covered in the How-To and I don't think it really has anything to do with creating a directory structure?
From the How To - There are currently no postload processing tools in place. If you have .tif files but want to make .jpg public, you should convert the files locally and upload the .jpg files.

> "Small batches of things named using unix conventions" is kinda in the vicinity of safe, maybe.

Not sure what to do with this?

**Comment by dustymc** [comment]
>don't think it really has anything to do with creating a directory structure?

Yes and no - a structure that leads to 15K large files also leads to a situation in which processing is limited. 

>Not sure what to do with this?

Me either!
