### ISSUE TITLE
How To needed - How To Create and Manage Higher Geography

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#246]
Please complete the form to the best of your ability. This will help us find the document and complete the update.

How To: suggested: https://handbook.arctosdb.org/how_to/How-to-Create-and-Manage-Geography.html)

In Github: suggested: https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_how_to/How-to-Create-and-Manage-Geography.markdown

The following need to be added to this How To

 - [ ] advice on what goes where
 - [ ] adding features, island groups and islands
 - [ ] looking for things that already exist
 - [ ] adding search terms
 - [ ] no special characters

**No need to complete below this point - these are reminders for the person working on the update**

When the above are complete, notify the Arctos Community of the update.

 - [ ] Social Media
 - [ ] Google Group
 - [ ] Newsletter

**Comment by dustymc** [comment]
This is https://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-geographic-terms-in-arctos

**Comment by Jegelewicz** [comment]
That does NOT provide direction for creating or editing geography - that is documentation about geography. "How To create and manage" would start out with "from the Arctos main menu select..." and then give direction from there. WHERE am I supposed to create new geography...

**Comment by Jegelewicz** [comment]
This is not applicable given that only Dusty can create geogrpahy now. Closing
