### ISSUE TITLE
How to create labels - HTML

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/documentation-wiki#256]
Now that we are transitioning away from CFR reports and using HTML tools, this page of the handbook is outdated:
https://handbook.arctosdb.org/how_to/How-to-Create-Labels.html

Does anyone have any resources or templates to get started with the new process that they could share?

Tagging @lkvoong, as suggested on Arctos report printer page

I started using https://wordtohtml.net/ to convert my labels to html, but I'm not sure how to get it to pull directly from Arctos once I have it formatted or how to print multiple labels per page.

Any suggestions on getting started or what resources to use are greatly appreciated. Thanks!

**Comment by Jegelewicz** [comment]
@Nicole-Ridgwell-NMMNHS is working this right now.

**Comment by wellerjes** [comment]
Thank you for the update!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I haven't actually started on html labels, I thought @dustymc and @lkvoong were still working on examples https://github.com/ArctosDB/internal/issues/37#issuecomment-1006210310. I was just going to pass my new paleo CFR label on to them . . .

**Comment by dustymc** [comment]
Yes, we're working on getting the basics sorted out; building the infrastructure, exploring css libraries, etc. 

Essentially nothing other than the base query from the CFR-based labels is going to translate. I still would not advise investing anything more into the CFR report system unless that's somehow completely unavoidable.

@wellerjes we just need some place to start, PDFs, word documents, pictures of your old labels, crayon on construction paper, WHATEVER gets the idea of the layout across probably works about as well as anything else. https://github.com/ArctosDB/internal/issues/37 is a good place for that.

The reporter is capable of returning CSV, feeding that to word/excel/gdocs/bartender/whatever you've been using is also a possibility if you're familiar with some sort of label-capable external app.
