### ISSUE TITLE
New tutorial for changing coordinates

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#266]
@ebraker I just uploaded a video tutorial to the Google Drive - Fix locality....

It should be trimmed and made pretty, but I don't have time, so can we just put it up as is?

**Comment by ebraker** [comment]
@Jegelewicz Totally! Thank you! We can also edit in Youtube studio at any point down the road (LMK if it is something simple and I'll just do it).

https://youtu.be/MM5lgfACD9k

**Comment by Jegelewicz** [comment]
Yay! Thanks!
