### ISSUE TITLE
Problem with Assigning Operator permissions

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/documentation-wiki#267]
Problem: I'm trying to set up user Cpowell98 as an operator for MSB. But I am unable to assign collection or role permissions. I get the following error:

![image](https://user-images.githubusercontent.com/14808196/159762712-52ce14d9-971a-4ef9-bf83-79ccbdddacc0.png)

![image](https://user-images.githubusercontent.com/14808196/159763131-3696427f-da12-4a86-b117-895342659b8f.png)

Priority: High. Preventing student access and impeding work.

**Comment by dustymc** [comment]
<img width="448" alt="Screen Shot 2022-03-23 at 10 46 44 AM" src="https://user-images.githubusercontent.com/5720791/159763348-fc5b1847-6215-4f60-9f8b-11acf2102d9b.png">


They need to act first. Please see the [documentation](https://handbook.arctosdb.org/documentation/users.html).

FYI this is a side effect of always being able to see roles, which was recently changed for some Issue.

**Comment by campmlc** [comment]
No - I got the error before I invited them as an operator. I clicked that
thinking it might make a difference.
Or have we now changed the sequence? It used to be that I would assign the
roles and permissions, and then invite them. Has that changed?

**Comment by dustymc** [comment]
The "Database User Status" is what I was trying to show.

It is not and never has been structurally possible to assign roles to a user until they've made it through the invitation process. That process creates the object to which roles are assigned.

**Comment by campmlc** [comment]
Maybe this page could use a step by step guide to this process, eg a
workflow. . No matter how many times I do this it never gets any easier.

**Comment by dustymc** [comment]
I believe that's the intent of https://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html (and how-tos in general).

**Comment by campmlc** [comment]
Needs to be a menu on the page.

**Comment by dustymc** [comment]
I think you're probably seeing the "you can create pagehelp" link?

**Comment by Jegelewicz** [comment]
I do think this is a good candidate for a workflow.

How's this? https://github.com/ArctosDB/new-collections/issues/new?assignees=&labels=&template=workflow--invite-an-new-arctos-operator.md&title=New+Operator+Invitiation

**Comment by dustymc** [comment]
>How's this?

Needs "check Database User Status" somewhere in (4).

**Comment by Jegelewicz** [comment]
Mo betta now?  https://github.com/ArctosDB/new-collections/issues/new?assignees=&labels=&template=workflow--invite-an-new-arctos-operator.md&title=New+Operator+Invitiation

**Comment by campmlc** [comment]
Fantastic! But I think we need to swap steps 1 and 2, because you need to add their Arctos login to their agent profile.  Also need to add step of them adding their email to their My Stuff Profile, which should occur right after they create a login.

**Comment by Jegelewicz** [comment]
> swap steps 1 and 2, because you need to add their Arctos login to their agent profile.

If we swap steps 1 and 2 you won't have an Agent to add their login to?

> adding their email to their My Stuff Profile

That is a step in the instructions for creating an account - https://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html#1-have-each-team-member-create-an-arctos-user-account

**Comment by campmlc** [comment]
Suggested revision:

1. Does the person have an Arctos Login that conforms to the specifications
[here](
https://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html#1-have-each-team-member-create-an-arctos-user-account
)?
    -  NO
         - [ ] Have them create one using the specifications [here](
https://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html#1-have-each-team-
                  member-create-an-arctos-user-account)
          - [ ] Have them send you their Arctos username.
          - [ ] Have them go to My Stuff and Profile and add their
affiliation and email address.
          - [ ] Have them send you their Arctos username and email address.
  -YES
           [ ] Have them send you their Arctos username and email address.

2. Does the person have an Arctos Agent?
    - [ ] YES - Add their Arctos username to the agent names in their
profile as login
    - [ ]  NO - Create an Agent for them. Make sure to include potential
variants of their name as akas, including variants without a middle
initial.  Add their Arctos username as a login name             in their
profile.

3. Invite the Arctos user to become an operator.
 - [ ] Go to https://arctos.database.museum/AdminUsers.cfm
 - [ ]  enter the Arctos username into the form
 - [ ]  select their username to administer their account
  -[ ] confirm they have an email address listed. If not, enter the one
they provided.
 - [ ]  Select "Invite as Operator"
 - [ ] an email will be sent to the new operator from Arctos with
instructions for accepting the invitation, after the user has accepted the
invitation, have them let you know they have completed this step

4. Assign permissions to the new Arctos operator
 - [ ] Go to https://arctos.database.museum/AdminUsers.cfm
 - [ ]  enter the Arctos username into the form
 - [ ]  select their username to administer their account
 - [ ] ensure the Database User Status is "Account open and active"
 - [ ] read the [documentation for user management](
https://arctos.database.museum/Admin/user_roles.cfm)
 - [ ] select "enable user management" (in the tiny blue font at the bottom
right of the screen).
 - [ ]  provide access to the appropriate collection(s)
 - [ ] ALL operators should be assigned the role coldfusion_user
 - [ ] assign other roles as needed - PLEASE ensure that any operator is
aware of documentation for all shared data roles!
 - [ ] email the new operator to let them know they re ready to begin work
in Arctos

**Comment by Jegelewicz** [comment]
> - [ ] Have them go to My Stuff and Profile and add their affiliation and email address.

This is already included here:
![image](https://user-images.githubusercontent.com/5725767/159789906-397c8dd3-86e1-4e13-970e-d943d7a851d3.png)

**Comment by campmlc** [comment]
But people miss it - I have to constantly remind. Doesn't hurt to add to
the workflow?

**Comment by Jegelewicz** [comment]
But the workflow is for the person making the invite, not the person being invited?
