### ISSUE TITLE
Arctos handbook header

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/documentation-wiki#27]
Can we make the Arctos Handbook header the same color green as the rest of the Arctos website theme where it has the menu (About Arctos, Join Arctos, etc.)? It would give the site a more consistent feel. Carol and Erica Ely (UNR student) agree. Thanks!

**Comment by mkoo** [comment]
First attempt was fairly hideous-- try same green but increase Sat maybe?

**Comment by mkoo** [comment]
Hyperlink header to home (index) page. If so, would favor removing the menu item "Home" to streamline the interface
