### ISSUE TITLE
Documentation update - geography

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/documentation-wiki#275]
Please complete the form to the best of your ability. This will help us find the document and complete the update.

ArctosDB.org url: 

https://handbook.arctosdb.org/documentation/higher-geography.html

The following need to be added/changed/deleted 

 - [ ] Most everything above Guidelines for Geographic terms in Arctos is wrong.
 - [x] https://github.com/ArctosDB/arctos/issues/5138 is The Plan; it could be turned into documentation

The following could use some more work

 - [ ] **indicate the section and provide details**
 - [ ] 

**No need to complete below this point - these are reminders for the person working on the update**

 - [x] Add a link to this issue at the top of the document (use "Add to current update request" as the text for the link)
 - [x] Add a link to this issue in the Community discussion section of the document (use "Github Issue #X" as the text for the link.)

When the above are complete:

 - [x] Comment the link created at the top of the document. (use  [//]: # before the link so it will not display on the page, but will remain in the code)
- [x] Remove the under construction bear banner if it is there

Notify the Arctos Community of the update:

 - [ ] Social Media
 - [ ] Google Group
 - [ ] Newsletter

**Comment by Jegelewicz** [comment]
The [example in the documentation for island](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1005324) gets me this

![image](https://user-images.githubusercontent.com/5725767/212745820-bb750c2c-39ff-43ff-a234-77c81d235ec9.png)

Same for parks - https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10004785

Can we get new examples and be sure they will work?

**Comment by Jegelewicz** [comment]
> Can I proceed with deleting everything below "Suggest removing everything below (although some might beuseful for eventual locality attributes?"?

@dusty said 

> No, some of it needs updated - primarily the guidelines, which can't be addressed until https://github.com/ArctosDB/arctos/issues/5417 is.

Put under construction bear above that point. But this needs to be made better sooner rather than later. I also need clarification - are FFF's NOT "Unassertable Higher Geography" and if they aren't what are they?

This documentation needs review by @dustymc @sharpphyl @mkoo

**Comment by sharpphyl** [comment]
I'll be happy to review the documentation but I'll be out of the country from January 18-February 1 with limited internet access.  Maybe some of the pending issues will be resolved by that time.  I'll check in then.

**Comment by mkoo** [comment]
This is on my to do list. OK if I draft a new page (that can be swapped for the current?) Or I can archive old so if you hate the new version we have a a way to get back to old version....

**Comment by Jegelewicz** [comment]
Github has the versions - feel free to replace.
