### ISSUE TITLE
Documentation update - Make clear what is required with coordinates

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#276]
> This doesn't appear obvious from either the Coordinates documentation page or the Bulkloader documentation page.

I'll put this in for an update!

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/data-migration/issues/1141#issuecomment-1279409985_

**Comment by Jegelewicz** [comment]
Please complete the form to the best of your ability. This will help us find the document and complete the update.

ArctosDB.org url: 

https://handbook.arctosdb.org/documentation/coordinates.html#georeference-method

https://handbook.arctosdb.org/documentation/bulkloader.html

The following need to be added/changed/deleted 

 - [ ] Make it clear which fields are required to bulkload coordinates

The following could use some more work

 - [ ] **indicate the section and provide details**
 - [ ] 

**No need to complete below this point - these are reminders for the person working on the update**

 - [ ] Add a link to this issue at the top of the document (use "Add to current update request" as the text for the link)
 - [ ] Add a link to this issue in the Community discussion section of the document (use "Github Issue #X" as the text for the link.)

When the above are complete:

 - [ ] Comment the link created at the top of the document. (use  [//]: # before the link so it will not display on the page, but will remain in the code)
- [ ] Remove the under construction bear banner if it is there

Notify the Arctos Community of the update:

 - [ ] Social Media
 - [ ] Google Group
 - [ ] Newsletter

**Comment by Jegelewicz** [comment]
Added text to indicate which fields go with which units in https://handbook.arctosdb.org/documentation/bulkloader.html

**Comment by Jegelewicz** [comment]
Added Pro Tip to https://handbook.arctosdb.org/documentation/coordinates.html

**Comment by Jegelewicz** [comment]
Also added terms to use with each unit type in the [code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctlat_long_units)

**Comment by dustymc** [comment]
I think everything that this touched is now wrong.

https://github.com/ArctosDB/arctos/issues/4716

**Comment by Jegelewicz** [comment]
How so? I need more than just "it's wrong" in order to make it right because clearly I don't know how this works anymore!

**Comment by dustymc** [comment]
https://github.com/ArctosDB/arctos/issues/4716

```
degrees dec. minutes needs

dec_lat_deg
dec_lat_min
dec_lat_dir
dec_long_deg
dec_long_min
dec_long_dir
```

**Comment by Jegelewicz** [comment]
Thank you, all updates made.

**Comment by dustymc** [comment]
>all updates made



https://handbook.arctosdb.org/documentation/bulkloader.html
<img width="852" alt="Screenshot 2022-11-28 at 3 27 14 PM" src="https://user-images.githubusercontent.com/5720791/204402102-87f7f773-d7a0-4237-860d-d6dbb18cc186.png">

https://handbook.arctosdb.org/documentation/coordinates.html
<img width="217" alt="Screenshot 2022-11-28 at 3 27 37 PM" src="https://user-images.githubusercontent.com/5720791/204402141-c5f6bc88-78a1-466a-af3c-8431fee0ae8c.png">

??

**Comment by Jegelewicz** [comment]
I don't know what is going on with the handbook, but I am not making any mnore edits until we have it figured out.

![image](https://user-images.githubusercontent.com/5725767/204403734-76c707b0-8c9a-47b6-8a58-9903f2de43d5.png)
 in Github lookslike 

![image](https://user-images.githubusercontent.com/5725767/204403784-3bf1c639-8a42-410e-8402-1d5775f2ff08.png)
in the handbook

See also https://github.com/ArctosDB/documentation-wiki/issues/282

**Comment by Jegelewicz** [comment]
![image](https://user-images.githubusercontent.com/5725767/204404057-297e03da-9841-4879-9e28-cc8ef1b847ca.png)
![image](https://user-images.githubusercontent.com/5725767/204404114-190693c8-92af-4204-9e06-daa38a09348d.png)

in Github but

![image](https://user-images.githubusercontent.com/5725767/204404204-16ed78a8-cd9c-4988-b66c-5fcd30e3bbe7.png)

in Documentation

**Comment by Jegelewicz** [comment]
I think that table does what was asked?
