### ISSUE TITLE
Add to Excel hates me

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/documentation-wiki#278]
I noticed some year-only dates in some of the fields in your file. Be careful with these, Excel will interpret these as 'days since 1900-01-01'. So the year 2005 will become 1905-06-27. We usually default to the latest possible value for these (e.g., 2005-12-31).

_Originally posted by @acdoll in https://github.com/ArctosDB/arctos/issues/5203#issuecomment-1289398550_

@dustymc suggests adding comment about this to the end of this 'Excel hates me. Help!' section

**Comment by ewommack** [comment]
Yes I hate this feature of excel. Stop messing with my dates.

**Comment by Jegelewicz** [comment]
Format them as text and Excel will leave them alone....

Also - the document needs a better title.

**Comment by Jegelewicz** [comment]
Added
