### ISSUE TITLE
add edit links from rendered handbook page to code in Github

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/documentation-wiki#28]
https://arctosdb.github.io/documentation-wiki/documentation/Accession.html should auto-link to https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_documentation/Accession.markdown with link text "edit" (or "manage" or etc.).

**Comment by Jegelewicz** [comment]
@dustymc both of those links 404. Is this still needed? If so, what was it for and what pages?

**Comment by dustymc** [comment]
Yea unstable URLs are a pain....

This was just an attempt to make it easy for people to get from the rendered HTML page (https://handbook.arctosdb.org/documentation/accession.html) to the markdown (https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_documentation/accession.markdown), where anyone with rights can edit. Still seems pretty useful, maybe beside your "Request Documentation Update" links.

**Comment by Jegelewicz** [comment]
OK - I thought that's what you were getting at and yes - I like it. I'll look at adding it to the pages in some "normal" way.

**Comment by Jegelewicz** [comment]
Suggested addition to every handbook page:

## Edit this Documentation

If you see something that needs to be edited in this document, you can create an issue using the link under the search widget at the top left side of this page, or you can edit directly <a href="https://github.com/ArctosDB/documentation-wiki/edit/gh-pages/_documentation/users.markdown" target="_blank">here</a>.

Adjust link for title of the page.

**Comment by Jegelewicz** [comment]
This section has been added to all "Documentation" pages and I am exhausted! Need to do this for Best practices and how tos, which will take a while.

**Comment by Jegelewicz** [comment]
Text for best practices

## Edit this Documentation

If you see something that needs to be edited in this document, you can create an issue using the link under the search widget at the top left side of this page, or you can edit directly <a href="https://github.com/ArctosDB/documentation-wiki/edit/gh-pages/_best_practices/Catalog-Record.markdown" target="_blank">here</a>.

**Comment by Jegelewicz** [comment]
All Best Practice pages now include a link to edit them.

**Comment by Jegelewicz** [comment]
The following text is for How-Tos

## Edit this Documentation

If you see something that needs to be edited in this document, you can create an issue using the link under the search widget at the top left side of this page, or you can edit directly <a href="https://github.com/ArctosDB/documentation-wiki/edit/gh-pages/_how_to/Barcode-Supplies.markdown" target="_blank">here</a>.

**Comment by Jegelewicz** [comment]
All editable pages in the Arctos Documentation now include the following at the bottom:

## Edit this Documentation

If you see something that needs to be edited in this document, you can create an issue using the link under the search widget at the top left side of this page, or you can edit directly <a href="https://github.com/ArctosDB/documentation-wiki/edit/gh-pages/_how_to/Barcode-Supplies.markdown" target="_blank">here</a>.

For anyone with edit access in the documentation-wiki repository in GitHub, the link from the word here should take you directly to the edit page for the document, making it very easy to commit simple changes to any Arctos documentation. So don't file an issue - just edit as necessary!
