### ISSUE TITLE
Updates not showing up in the handbook

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#282]
I made hundreds of updates to the handbook on Wednesday and none of them show up there. They usually appear within a few minutes. @mkoo what do I need to do?

**Comment by Jegelewicz** [comment]
I am pretty sure it is the various branches of howto - I updated hgpages, but possibly some other branch is being used for the handbook? This is a problem now and all of the edits I made refer to the ghpages branch - I don't want to have to make all of those again!

**Comment by mkoo** [comment]
Not sure but will check out -- which branch do you usually make your
changes-- might need to do some house cleaning too
MK

**Comment by Jegelewicz** [comment]
gh-pages

**Comment by Jegelewicz** [comment]
The updates to the documentation show up - it's the how to's that seem to be problematic.

**Comment by Jegelewicz** [comment]
Since Arctos was down, I had some time to mess around and I figured out what was causing the disruption in updates to the Handbook. It was an invalid date format in https://handbook.arctosdb.org/how_to/How-to-Link-Genetic-Data-To-And-From-Arctos.html After removing the empty date portion of the title box, everything updated.
