### ISSUE TITLE
Documentation update - How To Understand Portals

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#302]
Please complete the form to the best of your ability. This will help us find the document and complete the update.

ArctosDB.org url: https://handbook.arctosdb.org/how_to/understanding-portals.html

Github code: https://github.com/ArctosDB/documentation-wiki/edit/gh-pages/_how_to/understanding-portals.markdown

@dustymc does this need an update? 

The following need to be added/changed/deleted 

 - [ ] Can I still get stuck in a "portal" and if so, how do I get out now?
 - [ ] Can we call this "How To Understand Search from the Collections Page"? Portals is confusing and I'd like to use a more familiar term.
 - [ ] Anything else we could do to make this more helpful?

The following could use some more work

 - [ ] **indicate the section and provide details**
 - [ ] 

**No need to complete below this point - these are reminders for the person working on the update**

 - [ ] Add a link to this issue at the top of the document (use "Add to current update request" as the text for the link)
 - [ ] Add a link to this issue in the Community discussion section of the document (use "Github Issue #X" as the text for the link.)

When the above are complete:

 - [ ] Comment the link created at the top of the document. (use  [//]: # before the link so it will not display on the page, but will remain in the code)
- [ ] Remove the under construction bear banner if it is there

Notify the Arctos Community of the update:

 - [ ] Social Media
 - [ ] Google Group
 - [ ] Newsletter

**Comment by dustymc** [comment]
I think nuke the whole thing - "portals" are long gone (yay!), we're still using VPD but (mostly) internally (and PG calls it RLS), I think that just adds confusion at this point.

**Comment by Jegelewicz** [comment]
Agree - I'll deprecate and remove it form the How To index.

Thanks!

**Comment by mkoo** [comment]
archived
