### ISSUE TITLE
extra "when" typo and asserting this and that

### ISSUE THREAD

**Issue by gshugart** [ArctosDB/documentation-wiki#303]
From: https://handbook.arctosdb.org/best_practices/Agents.html
"Don’t create an Agent at all
Agents should exist only when they must carry **when** independent information. Attribute verbatim agent is functionally identical to most Agents. **If there is no compelling data which cannot be derived from activity to assert, not creating an Agent is almost always the correct choice.**"

Typo “when they must carry when” presumably delete second when. 

The highlighted sentence could be rewritten especially "activity to assert".  It seems to say "If knowing who/what the individual or entity was provides no significant data relevant to the specimen or record, then don't create an agent. E.g., Joe Smith found a dead squirrel and dropped in off on his way to work. So Joe Smith should not be designated an agent, let alone there is no need to parse the name, and Joe is simply relegated to verbatium agent, misc. comments, or simply “anon”? If this is a correct interpretation, then most salvagers/collectors on PSM specimens could be omitted or should be verbatims since they don’t provide any “compelling data” to the records or specimens. I assume "activity to assert" means that Joe could verify that he found a dead squirrel, but since his contact info was not provided there is no way to verify that he found the dead squirrel so he would be unavailable to assert the activity. Getting deep in the weeds on this one.

**Comment by Jegelewicz** [comment]
> Getting deep in the weeds on this one.

Yes - but that's good and I like your assessment of the situation...
