### ISSUE TITLE
Documentation update - Redirects?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/documentation-wiki#304]
Please complete the form to the best of your ability. This will help us find the document and complete the update.

ArctosDB.org url: https://handbook.arctosdb.org/documentation/redirect.html

Github code: **replace this text with the url of the Github code for the documentation. (example: https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_how_to/How-to-Create-a-New-Loan.markdown**
?

The following need to be added/changed/deleted 

 I tried to follow these instructions and failed to create a redirect. The example given in the text shows the format for the redirect bulkloader (old_path=/guid%), not the format for the manage redirects form, which only requires the "/guid%" path.  It would be good to fix that in both the documentation and on the tool itself. 
Once I figured that out, I got a response showing the two records - one old and one new path - with a delete button next to it. It wasn't clear what the delete button was for, or what I needed to do to approve or go forward with the redirect, or whether the redirect actually had been created. I had previously just encumbered the old record, but then I went ahead and deleted it to see if that made a difference, but when I search on that url, there is no redirect to the new one. Is there a lag? If so, we should state that.
If I have done something incorrectly, please explain.

![Screenshot 2024-03-20 13 10 53](https://github.com/ArctosDB/documentation-wiki/assets/14808196/2a815344-7113-447c-88d9-a9fa4644d26d)

The following could use some more work

 - [ ] see above.
 - [ ] 

**No need to complete below this point - these are reminders for the person working on the update**

 - [ ] Add a link to this issue at the top of the document (use "Add to current update request" as the text for the link)
 - [ ] Add a link to this issue in the Community discussion section of the document (use "Github Issue #X" as the text for the link.)

When the above are complete:

 - [ ] Comment the link created at the top of the document. (use  [//]: # before the link so it will not display on the page, but will remain in the code)
- [ ] Remove the under construction bear banner if it is there

Notify the Arctos Community of the update:

 - [ ] Social Media
 - [ ] Google Group
 - [ ] Newsletter

**Comment by campmlc** [comment]
So when I use the API by putting the full "old" term in the browser as https, the "new" record displays. 
But when I search on the "old" guid in Search Records, nothing appears. I would expect if someone were looking for the deleted/encumbered cataloged item by the guid or catalog number, the "new" record would appear in search results?

**Comment by Jegelewicz** [comment]
Please advise on how this needs to be updated - https://handbook.arctosdb.org/documentation/redirect.html

**Comment by mkoo** [comment]
HI Mariel, this screenshot shows that the redirect was already created, exists and is working (I tested that!) so the delete option is only if it needs to be recreated (because of some internet gerbil issue) or is wrong and needs to be redone. The instructions on the page says that-- cannot edit but you can delete and make a new one.

The handbook could repeat that but I think to make it more sustainable, we could add, "please read guidelines on tool page for latest instructions"
