### ISSUE TITLE
replace gone wild?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/documentation-wiki#32]
http://handbook.arctosdb.org/documentation/higher-geography.html#guidelines-for-creating-and-editing-geographic-terms-in-arctos (that anchor is a mouthful!) says...

...do not link to anchors in general articles, lists, maps, **../images**, or anything....

I assume some replace has added the ../. I'd be surprised if this is the only text occurrence of "images."

**Comment by mkoo** [comment]
Why are there strikethroughs on that page?
I will correct that.

is that anchor linked then? no, right?
I want to rename" Guidelines for Geographic Terms, please!

**Comment by dustymc** [comment]
>Why are there strikethroughs on that page?

It seemed like a good idea at the time, but turned out to be unworkable. Strikethrough is my attempt at keeping the history.

It is linked, but I can change the anchor.

**Comment by mkoo** [comment]
we can keep it... wasnt sure it was intentional

**Comment by dustymc** [comment]
Fixed at some point, I guess? Closing....
