### ISSUE TITLE
search should match any substring

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/documentation-wiki#33]
<img width="266" alt="screen shot 2017-02-23 at 1 50 57 pm" src="https://cloud.githubusercontent.com/assets/5720791/23280721/3019913c-f9cf-11e6-92e9-73e77cec551c.png">

does not find "specimen citations"

<img width="257" alt="screen shot 2017-02-23 at 1 51 57 pm" src="https://cloud.githubusercontent.com/assets/5720791/23280754/498bc7ca-f9cf-11e6-80c8-cef7fbc462d1.png">

and it should - we can't expect users to guess the first characters of some arbitrary string.

**Comment by tigerhawkvok** [comment]
Extended search to 25 results, and instead of an alphabetical-by-collection result list, it's first sorted by substring match and then by Levenshtein distance from the search phrase.
