### ISSUE TITLE
logs?

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/documentation-wiki#34]
Is anyone monitoring logs? Clicking the lily-pad at http://arctosdb.org/ still 404s

**Comment by mkoo** [comment]
no I have not! that link was a casualty of Carla's reordering of pages. Are
there many more, Carla?
that widget is fixed. Just send me others you note and i'll try to update
but there is no systematic way since I dont know all the changes she did.

**Comment by Jegelewicz** [comment]
Can we close this?

**Comment by mkoo** [comment]
close please!
