### ISSUE TITLE
funky link

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/documentation-wiki#35]
The handbook link has a new tab/external link icon (at least in my head!), but it opens in the same window and isn't REALLY external. Not sure the icon is necessary.

It's also opening the .io page, which seems like an unnecessary redirect.

**Comment by tigerhawkvok** [comment]
Ah, this refers to arctosdb.org, not the handbook itself.

![image](https://cloud.githubusercontent.com/assets/165937/24415175/719016a6-1395-11e7-8ea2-855e8a123a5e.png)


Not sure what the arctosdb.org issue report area is ...

**Comment by mkoo** [comment]
Belatedly closed. fixed at wp site
