### ISSUE TITLE
fix link to address page

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/documentation-wiki#36]
From the documentation ToC, link to Address (sub under Agents) needs to be updated. Not sure where the website is pulling the ToC content from or else I'd fix.

**Comment by tigerhawkvok** [comment]
@ekrimmel FYI some pages have autogenerated ToC, but the doc page is manual at https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_documentation/index.html .

**Comment by ekrimmel** [comment]
thx!
