### ISSUE TITLE
print stylesheet

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/documentation-wiki#37]
@tigerhawkvok would it be a pain to make/adjust a print stylesheet for the handbook? Something that would just ditch the footer and site navigation for printing? We have older volunteers who will always prefer to have printed copies of instructions, and it'd be cool if they were just a little cleaner than the site currently prints.

**Comment by tigerhawkvok** [comment]
@ekrimmel I just saw this. Waaaaay late. Sorry, let me tackle this.

**Comment by tigerhawkvok** [comment]
@ekrimmel I left the footer on the page in a reduced form but removed almost everything else other than the content (which I expanded to a full page).

See this sample:

[Accessions.pdf](https://github.com/ArctosDB/documentation-wiki/files/1055519/Accessions.pdf)

Please review and close this issue if you think that all the important bits have been addressed!

**Comment by ekrimmel** [comment]
Thanks! Looks good to me.
