### ISSUE TITLE
Join/Maintenance documentation

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/documentation-wiki#38]
http://handbook.arctosdb.org/how_to/Starting-as-a-New-Collection-in-Arctos.html exists but is heavily grbio-centric and otherwise mostly applies to the things "we" need to initially establish a collection. 

Somehow (expand above or new/additional document??) we need documentation on establishing and maintaining a collection - things curator-type users should be doing. 

EDIT: "intro to Arctos" packet should contain a link to the sitemap (http://handbook.arctosdb.org/documentation/useful_documents.html), which provides a high-level view of some Arctos capabilities that users are probably not aware of.

Perhaps an annual (??) "review your metadata" reminder could be useful?

* manage collection
    * collection contacts and associated emails - I suspect some collections don't get alerts, some alerts go to users who are no longer active, etc.
    * links to loan forms, collection web pages, etc. should be checked
    * description, citation should be reviewed
* participation
    * github - what used to happen on the Arctos list has mostly moved to Github. Does everyone get notifications? Also @mentions - I try to tag anyone who's input might be critical, but usually can't find anyone who isn't a user (https://github.com/orgs/ArctosDB/people)
    * working group/steering committee - as mentioned by @ekrimmel  in https://docs.google.com/document/d/1-dhn1HNKA2eFeTfjJxIWFaCuBg9SQWoIRNn7YrTXzmk/edit many users probably don't know these things exist/how to participate/etc.
* GenBank - collections need to register with GenBank to make reciprocal links work
* Other stuff, probably - what do people need to know to make better use of Arctos?

**Comment by DerekSikes** [comment]
All this makes sense to me.

**Comment by ekrimmel** [comment]
Agreed we need more/better documentation for what the collection mgr/curator should be doing.

I would also like to see an annual "review your metadata" email reminder. Would it make sense to pull Arctos collection metadata from the VertNet IPT? Or perhaps better to do the reverse? I think it's inefficient and inaccurate to have to manage the very similar information on Arctos, the IPT, and iDigBio. With more integration most of the scope-type metadata on the IPT (temporal/geographic/taxonomic, etc.), and all of the statistics (occurrence records, media records, etc.) could be at least semi-automatically populated by Arctos.

i.e. we could/should be keeping track of our mammal collection metadata in four places (plus its institutional parent on GRBio), and the only one that's hands-off is GBIF:

![mamm_coll_metadata](https://cloud.githubusercontent.com/assets/11165319/25397772/232a8a3e-29af-11e7-9dff-1c47d27113b3.JPG)

This has totally turned into my personal annoyance with managing metadata, but I do think Arctos could in the future become a better way to help us do so.

**Comment by dustymc** [comment]
>annual "review your metadata" email reminder

Is that something Arctos should send out (if so maybe just a URL + short note??) or should the AWG schedule that (could be more customized) for some yearly meeting or ??

>pull Arctos collection metadata from the VertNet IPT

That would only help some collections - I don't think everyone shares via ipt.

>Or perhaps better to do the reverse?

That's my preference. I'm happy to build webservices, add data/structure, or whatever to make it happen.

>GRBio

People come and go, get new addresses, etc. Arctos generally gets updated because it does something direct (eg, email reminders). We could easily make that available to grbio (and/or whomever wants it).

**Comment by campmlc** [comment]
An email reminder is good, especially with links to where we should be
checking.
GRBio needs to be checked periodically also - do they send out reminders?
I've only seen an email if I change something.

**Comment by Jegelewicz** [comment]
> http://handbook.arctosdb.org/how_to/Starting-as-a-New-Collection-in-Arctos.html exists but is heavily grbio-centric and otherwise mostly applies to the things "we" need to initially establish a collection.

Agree and I think this is no longer very useful/information is covered elsewhere. Suggest we remove from How-To.

See http://handbook.arctosdb.org/resources/ : Joining Arctos section.
http://handbook.arctosdb.org/how_to/How-to-Manage-a-Collection-in-Arctos.html

**Comment by Jegelewicz** [comment]
> 
>     collection contacts and associated emails - I suspect some collections don't get alerts, some alerts go to users who are no longer active, etc.
>     links to loan forms, collection web pages, etc. should be checked
>     description, citation should be reviewed

Added to http://handbook.arctosdb.org/how_to/How-to-Manage-a-Collection-in-Arctos.html
