### ISSUE TITLE
Add two terms to Taxon status Code table

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/documentation-wiki#39]
We use World Registry of Marine Species (marinespecies.org) as our primary authority for valid taxon.  WoRMS uses "accepted" and "unaccepted" as the taxon status.  It would be helpful if these terms were added to the six in the Documentation for code table TAXON_STATUS.  

Example: http://marinespecies.org/aphia.php?p=taxdetails&id=578734 (unaccepted)
http://marinespecies.org/aphia.php?p=taxdetails&id=403707 (accepted)

We do not need to add the reason the term is unaccepted.

Now that the entries we can make in taxon_status are limited to those in the code table, a dropdown listing those terms would be very helpful.

THX!

**Comment by dustymc** [comment]
Moved to https://github.com/ArctosDB/arctos/issues/1126
