### ISSUE TITLE
Arctos down?

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/documentation-wiki#43]
I receive this error when I try to access arctos.database.museum:

An error occurred while processing this page! Error Executing Database Query.
[Macromedia][Oracle JDBC Driver][Oracle]ORA-00604: error occurred at recursive SQL level 1 ORA-01653: unable to extend table SYS.AUD$ by 8192 in tablespace SYSTEM ORA-02002: error while writing to audit trail ORA-00604: error occurred at recursive SQL level 1 ORA-01653: unable to extend table SYS.AUD$ by 8192 in tablespace SYSTEM

**Comment by mkoo** [comment]
Yes, Arctos is effectively down for the moment. We have an email thread
with TACC to see if something can be done in the absence of Dusty.

Sorry about this-- I know people have work to do! Will update if I know
something substantial!

**Comment by mkoo** [comment]
Chris Jordan was able to give us a little more leeway but not a permanent
fix.

But for now, we are back online-- yay! No data was imperiled but Dusty will
need to address some backend issues when he gets back in the saddle.

Thanks for your patience! And whew!
