### ISSUE TITLE
I added a how-to, now what?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#44]
I just added https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/How_to_Document_Collection_Usage.markdown
What is the process for making new how tos visible to everyone?

The instruction say that "Pages will dynamically appear on the How to Index page and be searchable on the Arctos Handbook site now. " but I don't see my addition in the list.  I assume it takes some time?  Just want to make sure I haven't somehow missed a step.
Thanks!

**Comment by ekrimmel** [comment]
@Jegelewicz I moved your markdown file into the "_how_to" folder (to be auto indexed) and changed the filename to use dashes instead of underscores (for consistency).

See it on the handbook [here](http://handbook.arctosdb.org/how_to/How-to-Document-Collection-Usage.html).

**Comment by dustymc** [comment]
@ccicero @mkoo @tigerhawkvok is some sort of "new and updated" weekly (or ??) notification possible? I suspect a lot of things are not discovered for some time, and most everything here could benefit from more people seeing it and potentially contributing.

**Comment by tigerhawkvok** [comment]
I'll take a look and see if Jekyll can expose modified times to show a quick "what's new" on the home page.

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Jegelewicz** [comment]
@ekrimmel thanks! I thought that was the folder I was in when I created the thing.  Where was it?

**Comment by ekrimmel** [comment]
@Jegelewicz just up one, in "documentation-wiki"
