### ISSUE TITLE
Understanding Oracle errors

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/documentation-wiki#45]
Somewhere we have a list of these? 
I'd like to add the following error:
An error occurred while processing this page! 
Error Executing Database Query. 
[Macromedia][Oracle JDBC Driver][Oracle]ORA-01427: single-row subquery returns more than one row

I got this error when trying to bulkload loan items using only barcodes. The problem was that the same barcode was associated with two different cataloged items because of transcription error in the orginal data file. I found it going record by record. It would be good to have some sort of screening tool to detect which records are causing problems.

**Comment by dustymc** [comment]
http://handbook.arctosdb.org/documentation/understanding-errors.html#single-row-subquery-returns-more-than-one-row
