### ISSUE TITLE
How-to-Manage-a-Collection-in-Arctos

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/documentation-wiki#47]
Hi all,
Do we have any draft documentation to create this page? It is currently blank.

https://github.com/ArctosDB/documentation-wiki/wiki/How-to-Manage-a-Collection-in-Arctos

We have links to it from 
http://handbook.arctosdb.org/how_to/How-to-Start-a-New-Collection-in-Arctos.html

**Comment by dustymc** [comment]
I think it's http://handbook.arctosdb.org/how_to/How-to-Manage-a-Collection-in-Arctos.html (I just searched "collection"). Maybe we should merge that with http://handbook.arctosdb.org/how_to/How-to-Start-a-New-Collection-in-Arctos.html?

**Comment by Jegelewicz** [comment]
Seems resolved at http://handbook.arctosdb.org/how_to/How-to-Manage-a-Collection-in-Arctos.html

**Comment by Jegelewicz** [comment]
Re-opening because may need to be expanded.

Need to add recommendation to have a loan contact and data quality contact so that someone will get notifications about annotations and past due loans? or does this only matter in the loan form?

Also - always add Dusty as technical contact...

**Comment by Jegelewicz** [comment]
Added to How-To

> It is recommended that every collection have at least one Data Quality and one Loan Request contact. Technical Support contact should be given as Dusty L. McDonald unless otherwise advised.
