### ISSUE TITLE
dead links on documentation

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/documentation-wiki#48]
1. "(the “Arctos Ecosystem”)" on https://arctosdb.org/about/ 404s

2. This is too common, and embarrassing. Someone needs to be watching logs. I'll do it if nobody else is willing and I can get access to them.

**Comment by mkoo** [comment]
I agree! let me see if I can run a link checker/tester on the site.

**Comment by mkoo** [comment]
Ran a link checker-- found 5 more dead/old links and fixed.
