### ISSUE TITLE
How-to-Use-Github-for-Arctos improvements

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/documentation-wiki#49]
https://github.com/ArctosDB/documentation-wiki/wiki/How-to-Use-Github-for-Arctos

I think we should clarify that GitHub issues are the primary/most reliable form of communication with "us" and encourage all users to subscribe to GH Issues.

In "What You Can Do in GitHub" - 

* suggest we reword "Curators/Collection Managers" to be much more inclusive. ("Anyone actively working with Arctos"??)
* Suggest we provide a pathway to allow users who file Issues to add labels and milestones (do we need a new GH user role, or are those the same folks who edit documentation?).
* Add a section on Issue prioritization (use "like" to vote??)
* Do we need to do something with categorizing issues, eg, the "function-..." labels, to get the right people involved?
* Add a section on issue finalization. Tentative suggestion:
    * start a doodle poll for some time sufficiently in the future (week? Month??), paste it into the issue, hold an issue-specific "AWG task force meeting," whoever shows up resolves the Issue

@KyndallH

**Comment by ekrimmel** [comment]
> Add a section on issue finalization. Tentative suggestion:
start a doodle poll for some time sufficiently in the future (week? Month??), paste it into the issue, hold an issue-specific "AWG task force meeting," whoever shows up resolves the Issue

I suggest we have a trial "AWG task force meeting" sometime after Thanksgiving or in early December focused on resolving issues related to managing geography. It's a topic that applies to everyone, and has come up in various "needs discussion" issues lately. We could get through as many of the following issues as time allows:

- [watershed #1273](https://github.com/ArctosDB/arctos/issues/1273)
- [Geography: minimum "size" #1278](https://github.com/ArctosDB/arctos/issues/1278)
- [geography: duplicate/redundant terms #1315](https://github.com/ArctosDB/arctos/issues/1315)
- [geography: documentation request #1316](https://github.com/ArctosDB/arctos/issues/1316)
- [geography<-->specimen guidelines #1107](https://github.com/ArctosDB/arctos/issues/1107)
- [USGS quad WKT #1029](https://github.com/ArctosDB/arctos/issues/1029)
- [Locality Feature #1034](https://github.com/ArctosDB/arctos/issues/1034)
- [How to add a geographic Feature #1010](https://github.com/ArctosDB/arctos/issues/1010)
- [turn multiple coordinates into WKT #831](https://github.com/ArctosDB/arctos/issues/831)

There are probably other "needs discussion" issues related to geography too, but this is where I stopped...

**Comment by KyndallH** [comment]
If we get a what/when/where figured out within the next week, it can do an official invite for it in the inaugural Arctos newsletter.

**Comment by ekrimmel** [comment]
Fancy!!

**Comment by campmlc** [comment]
I agree with all those suggestions.  I also think we should add this
content/link to the newsletter.

**Comment by mkoo** [comment]
I like all these suggestions. Can I start a doodle poll for early December?
Sorta a special AWG meeting for geography issues?

**Comment by dustymc** [comment]
I made some changes to https://github.com/ArctosDB/documentation-wiki/wiki/How-to-Use-Github-for-Arctos - it could still use some clean-up.

@mkoo I think the poll should be in the meta/meeting-issue. I guess that's this so here it is: https://doodle.com/poll/iu64mf6dzikf4vaz.

Perhaps is should also be in the individual issues so the right people get alerts? Or in the newsfeed https://github.com/ArctosDB/arctos/issues/1327, which I could push out now)?

**Comment by mkoo** [comment]
Whatever you think best-- newsfeed? or to the Arctos list? (is there a
comprehensive list for non and AWG members?)

**Comment by dustymc** [comment]
>newsfeed

It just went to prod - try it out!

**Comment by Jegelewicz** [comment]
Documentation updated #64  and a "Resource" Created. Can we make the "headers" on the Resources page linkable? @mkoo 

Also, would it be possible to change the title of this page to reflect what it actually is?

Perhaps: How To's by Topic
