### ISSUE TITLE
REQUEST: loan type clarification

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/documentation-wiki#51]
ref: https://youtu.be/Zeegl0eyqkg?t=2867

I don't think http://handbook.arctosdb.org/documentation/loans.html is clear.

Essentially,

1) did touch specimen part-->not a data loan
2) did not touch specimen part-->is data loan

Photographing a specimen is NOT a data loan - they handled specific parts, may have damaged/misplaced those items, etc.

Using the digital photos produced by ^^ that usage IS (probably) a data loan - they didn't touch anything.

Using PRINT photos (or high-resolution digitals not available from Arctos etc.) may be a "real" loan - this probably varies by collection, and the physical photo or storage device or whatever may be cataloged as a part.

Could someone clarify the documentation please?

**Comment by AJLinn** [comment]
This summer when Dusty was cleaning up the data vs regular loans, we created a "media" loan type, which you can see i the [code table](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTLOAN_TYPE)

> Using the digital photos produced by ^^ that usage IS (probably) a data loan - they didn't touch anything.

Based on the documentation for "media" in the CTLOAN_TYPE the use of digital images (whether they are existing files you have already or ones that a researcher took during an earlier visit to your collection, as documented by your "in house loan"), this should not be a data loan but rather a media loan.

I'd be willing to work on a draft of the documentation for this if someone wants to walk me thru the process of doing so...

**Comment by dustymc** [comment]
Documentation-documentation is http://handbook.arctosdb.org/how_to/How-to-Contribute-Content-to-Arctos-Handbook.html. 

>should not be a data loan but rather a media loan

I think that varies by collection practices. I certainly don't see any compelling reason to go one way or another.

The functional difference is in relationships. 

* In the case of data loans, loan_item.collection_object_id references cataloged_item.collection_object_id. Cataloged items are by definition abstract objects - they're whatever some Curator felt like cataloging. http://handbook.arctosdb.org/documentation/catalog.html#understanding-cataloged-items
* In the case of non-data loans, loan_item.collection_object_id references specimen_part.collection_object_id. Specimen parts are by definition physical things - but I think some collections "cheat" to simplify tracking things like digital media. http://handbook.arctosdb.org/documentation/parts.html

And that's technically all lies too. All loan items reference coll_object.collection_object_id, and collection objects include both cataloged items and specimen parts. I don't think an operator should need to know the intricacies of the data model to know what type of loan they're dealing with, but my attempts at simplification seem to inevitably lead to confusion or ambiguity - so HELP!!

**Comment by droberts49** [comment]
I'm unclear about the data loan category. If Arctos is accessible online, someone could query and download specimen data on their own; there wouldn't be a formal loan for them to access data. We haven't used them here and I'd like some clarification on these.

**Comment by dustymc** [comment]
The origins of data loans are briefly described in http://handbook.arctosdb.org/documentation/loans.html#type.  Even shorter version:


* Found publication vaguely citing Arctos
* ...
* Created Arctos loan of type “data”
* [added]  scientific names cited in publication

>The collections used, even though there was no formal loan request and no physical specimen usage, receive quantifiable credit for specimen data used. Future Hieracium added to Arctos will not be included in this loan, so it will be possible to quickly identify specimens which could not have been used, even though the lack of citations in the paper makes it impossible to determine which specimens were actually used. Additionally, if current Hieracium specimens are later determined to be some other species, those data will remain as part of the loan, perhaps explaining yet-undetected anomalies in the publication.

**Comment by Jegelewicz** [comment]
Closing this now that we have https://handbook.arctosdb.org/best_practices/Loan_Type.html
