### ISSUE TITLE
ecosystem - edit request

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/documentation-wiki#54]
Can someone edit https://arctosdb.org/about/details/ecosystem/?

Arctos now actively communicates with wikidata, GNI (part of globalnames.), marinespecies.org (WORMs), EOL, and GBIF in attempting to validate taxonomy.

**Comment by Jegelewicz** [comment]
Can that page be modified via this repo? I don't think it can, so assigning to Michelle.

**Comment by dustymc** [comment]
Arctos is also using worms data for local classifications (eg, specimen taxonomy) and creating taxa as they are created in worms

**Comment by Jegelewicz** [comment]
Added WoRMS - closing
