### ISSUE TITLE
Add an attribute 

### ISSUE THREAD

**Issue by diannakrejsa** [ArctosDB/documentation-wiki#57]
I am part of a new collection coming into Arctos, the Angelo State Natural History Collections (GUID Prefix: ASNHC:Mamm and Herb right now). I am requesting an addition of an attribute to the CTCOLL_OTHER_ID_TYPE code table. Our tissue numbers are ASK, which is defined as "Angelo State Karytoype Number," a frozen tissue collection number for the Angelo State Natural History Collections. 

Thanks,
Dianna

**Comment by Jegelewicz** [comment]
Moving to Arctos issues
