### ISSUE TITLE
Update 'How to Create Arctos Team' page

### ISSUE THREAD

**Issue by srobson4** [ArctosDB/documentation-wiki#60]
Suggest changing title to "How to create and manage your arctos team" and add the follow at the end:

5. Managing and Reviewing Operator Roles and Permissions

- Go to Reports/Services dropdown>choose View Statistics> select Operator Contact/Operator Report
- Select your collection in the GUID prefix drop down and click the go button
- Review report of operators and assigned roles. 
- In this report you can manage user accounts and add/remove permissions.

**Comment by Jegelewicz** [comment]
I'll look into this!

**Comment by Jegelewicz** [comment]
Done!
