### ISSUE TITLE
Fix Contact Links on ArctosDB

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#65]
Can we please fix these links:

Arctos down? Send an email to one or more below:

    arctos.database [at] gmail.com
    ctjordan [at] tacc.utexas.edu
    help [at] tacc.utexas.edu

on https://arctosdb.org/join-arctos/contacts/

**Comment by mkoo** [comment]
Not sure what you mean 'fix'? make them hyperlinks? (we were being cautious
of spammers harvesting emails from websites)
Or something else I'm missing?

**Comment by Jegelewicz** [comment]
OH - I wasn't aware of that - not sure they are very helpful the way they are structured, but I guess it makes sense???

**Comment by mkoo** [comment]
Well, it's a common means of structuring email links so they remain plain
text and only (supposedly) human-harvestable. That is all debatable
nowadays. Plus spammers have much richer fields to harvest your email; they
can also just buy a bunch easily. So perhaps this is 1990's thinking....
I'll take a poll with the other programmers and see what they think!

**Comment by Jegelewicz** [comment]
Thanks!

**Comment by dustymc** [comment]
Please either keep the arctos.database email obfuscated or remove it from the list.

**Comment by mkoo** [comment]
let's keep as is.
