### ISSUE TITLE
Navigation framework for the new Arctos Docs site

### ISSUE THREAD

**Issue by tigerhawkvok** [ArctosDB/documentation-wiki#7]
![screenshot-idratherbewriting com 2016-06-15 14-02-35](https://cloud.githubusercontent.com/assets/165937/16097361/4fcce23e-3302-11e6-87a8-888648430e3a.png)

**Comment by mkoo** [comment]
Specifically sidebar navigation and table of contents (although looking at
that again, it seems like TOC is just anchored links).

Ideally sidebar navigation is selfbuilding based on *.markdown files in
directories

**Comment by mkoo** [comment]
New proposal is to have left sidebar serve as persistent TOC to navigate all pages (H1). A new righthand sidebar will be to navigate all the inpage H2-H6 subsections on the page.

**Comment by tigerhawkvok** [comment]
I started playing with this but it was already feeling ungainly at this stage. However, I'm actually quite fond of this behaviour:

![image](https://cloud.githubusercontent.com/assets/165937/17536756/1f08a7b2-5e4c-11e6-9d65-6b1908d94857.png)

![image](https://cloud.githubusercontent.com/assets/165937/17536762/2b774fee-5e4c-11e6-9803-ee77e875ab79.png)

**Comment by mkoo** [comment]
The left side padding still gets in the way of content-- see below in red circle. There's free real estate on the right so seems like we are not space limited. But that obscuring of content is crazy annoying!

![screenshot-arctosdb github io 2016-12-09 12-48-07](https://cloud.githubusercontent.com/assets/2523089/21064183/541b5432-be0e-11e6-8ee3-cecdc067a0dc.png)
