### ISSUE TITLE
Need update and cleanup to arctosdb.org

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/documentation-wiki#72]
After drafting an update the Taxonomy section of the primary Arctos website (arctosdb.org), I looked at how it would fit into the overall website.  Unhappily, I found more than a dozen dead links (I have a list).  This website is a primary marketing tool to secure new members and dead links here may be interpreted by potential members to mean there are similar problems within the database itself.

Additionally, I personally find the website awkward to navigate with duplicate links to pages within the website and elsewhere.  There's some really good information on the website but some of it is buried.  There is also some very out-of-date or erroneous information.  And there is some missing information that would be helpful to anyone considering Arctos. 

Since a presentation is planned at SPNHC this spring, we'll want the website to be in the best possible condition.  I'm happy to make suggestions (from a marketing perspective) and draft copy.  Who is the (probably already overworked) person who would actually implement them?  Who needs to approve changes to the website?  And who can write copy for topics I'm not familiar with?  

I see this as a high priority as potential members may be looking at our website every day (and comparing it to Specify, EMu etc.)

**Comment by mkoo** [comment]
I agree with Phyllis!
I can help make the changes but I think we should get a bunch of the
proposed changes all out there so we can make a concerted overhaul instead
of me just picking at it.

Maybe we should have a subgroup meet at the next Issues meeting? (oh crap,
I cant make it....) maybe Tuesday April 2?

**Comment by mkoo** [comment]
PS. I will run a deadlink scan as prep for the meeting... we should try to
fix those at a minimum

**Comment by sharpphyl** [comment]
Thanks for jumping on this.  Tuesday, April 2 is fine with me.  Time and place?  If you want, I'll share some outline ideas once the group is formed.

If you can do a deadlink scan, that's great and more inclusive than my checking.  You may want to check within arctos.database.museum and the handbook too.  Here's my list which is very messy since I was copying from the website and into Word.  If you can't find something, let me know.

![image](https://user-images.githubusercontent.com/15368365/54555616-bbf9e680-497c-11e9-8be4-3bc11a0071f3.png)

![image](https://user-images.githubusercontent.com/15368365/54556100-c072cf00-497d-11e9-8970-615db6510edd.png)

https://bnhmwp.berkeley.edu/arctos/join-arctos/data-migration/ from Join Arctos page

![image](https://user-images.githubusercontent.com/15368365/54555038-81437e80-497b-11e9-9f5c-100da45b0a67.png)

![image](https://user-images.githubusercontent.com/15368365/54555902-50644900-497d-11e9-9d09-2c7bc44168e2.png)

![image](https://user-images.githubusercontent.com/15368365/54555117-adf79600-497b-11e9-9221-d525e874b1c5.png)

![image](https://user-images.githubusercontent.com/15368365/54555133-ba7bee80-497b-11e9-9f62-e6411b47dbbe.png)

![image](https://user-images.githubusercontent.com/15368365/54555152-c49ded00-497b-11e9-9d23-61afae953bda.png)

![image](https://user-images.githubusercontent.com/15368365/54555186-d089af00-497b-11e9-8521-96ba882a8b6b.png)

![image](https://user-images.githubusercontent.com/15368365/54556028-9caf8900-497d-11e9-9c1e-99a297ee3658.png)

Arctos News: 
![image](https://user-images.githubusercontent.com/15368365/54555229-e4cdac00-497b-11e9-8998-918e92fd3404.png)

![image](https://user-images.githubusercontent.com/15368365/54555386-3bd38100-497c-11e9-8f40-34424395adee.png)

**Comment by dustymc** [comment]
>check within arctos.database.museum 

I get 404 notifications and would probably notice dead links. (Help always appreciated - https://github.com/ArctosDB/arctos/issues/1872)

**Comment by mkoo** [comment]
OK I ran a bunch of scans on arctosdb.org (ONLY that one since
arctos.database.museum is a whole 'nother kettle of fish in Dusty's hands)
while eating lunch and cleared up a bunch of internal links that was giving
404s --  I'm certain that they would include the ones you just copy/pasted
-- so those are fine. The rest of the errors are non-fatal issues
(false-positives really)

I did remove some of the circular extra menu tabs but that doesnt mean we
are still serving up info in the best way but at least now the weeds are
cleared for a more sane pruning job.
let me see if I can send an invite in a clear spot on the calendar....

**Comment by sharpphyl** [comment]
Much better. Thanks.  Only found one invalid link.

About Arctos/FAQ/How to Upload Media to TACC is 

![image](https://user-images.githubusercontent.com/15368365/54571268-87e7eb00-49a7-11e9-88b4-8a1306b9e158.png)

 but should be 

http://handbook.arctosdb.org/how_to/How-to-Upload-Media-to-TACC.html

**Comment by mkoo** [comment]
Thanks and fixed.

**Comment by sharpphyl** [comment]
Michelle, can you upload the attached update to the section in Nitty Gritty on Taxonomy at https://arctosdb.org/about/details/taxonomy/?  After we review the whole website, I think it will move this to another area, but the content should still be accurate.  Thanks.

[Taxonomy - Nitty Gritty 16 March 2019.docx](https://github.com/ArctosDB/documentation-wiki/files/2992178/Taxonomy.-.Nitty.Gritty.16.March.2019.docx)

**Comment by dustymc** [comment]
Neat - except the WoRMS part isn't accurate. Those data are synchronized constantly via webservice, the download was only used once.

**Comment by sharpphyl** [comment]
Thanks for the review.  I made that correction in the document below.  Let me know if it's not yet accurate.

[Taxonomy.-.Nitty.Gritty.16.March.2019.corrected.21.Mar.2019.docx](https://github.com/ArctosDB/documentation-wiki/files/2992788/Taxonomy.-.Nitty.Gritty.16.March.2019.corrected.21.Mar.2019.docx)

**Comment by Jegelewicz** [comment]
It makes the hierarchical tool sound soooooo easy.....but I'm OK with it.

**Comment by sharpphyl** [comment]
Maybe one day it will be easy!

**Comment by sharpphyl** [comment]
Michelle,
Do you still want to pull together a meeting to discuss the Arctos website?  Not sure what it's priority is with everything else going on, but with SPNHC coming soon, it would seem of value to work on it.

**Comment by sharpphyl** [comment]
@mkoo , Are you the one who would upload the above Taxonomy document to replace what's currently under Nitty Gritty/Taxonomy?  I don't think I'm supposed to mess in the arctosdb.org website - nor do I have any idea how to do that.

**Comment by mkoo** [comment]
Phyllis, yes I can do this but we had some database moves on the server so
I have been waiting for the dust to settle before making changes to the
wordpress site.

**Comment by mkoo** [comment]
ok I'm testing out the new move and updated the page:
https://arctosdb.org/about/details/taxonomy/

Let me know if it looks the way you intended, but reads well!

**Comment by campmlc** [comment]
Looks great, thank you, Phyllis and Michelle!
A couple of comments:
1) Berkeley Mapper is still broken - any chance of having it functional
before the SPNHC and taxon meetings starting in May?
2) The fully integrated taxon example
<http://arctos.database.museum/name/Haringtonhippus%20francisci> has two
identical relationships - why is that? If both are necessary, can we
clarify that these are somehow reciprocals? Dusty?
3) Linnean needs an extra a  = Linnaean

Our Arctos Institutions map is starting to look amazing!

**Comment by dustymc** [comment]
That's not BerkeleyMapper, that's https://github.com/ArctosDB/arctos/issues/2011

>identical relationships

It doesn't have identical RELATIONSHIPS - there's a primary key - but I see what you're saying. I'll get that with https://github.com/ArctosDB/arctos/issues/1866 - feel free to prioritize.

**Comment by dustymc** [comment]
"Automatically updated each month with the WoRMS aphiaID." should be "automatically updated as WoRMS changes with the WoRMS API" er sumthin - there's a <24h delay (plus potentially some processing time, although I don't think that's ever happened), not a month.

**Comment by mkoo** [comment]
Fixed the misspelling.

And changed the last sentence in that paragraph to:

```
It is automatically updated as WoRMS changes via the WoRMS API within 24 hours.
```

**Comment by sharpphyl** [comment]
Thanks so much for everyone's feedback and corrections.  It looks great.  But as Mariel pointed out, I may not have chosen the best "fully integrated taxon example."  From a bit of research, the taxon Equus francisci  should have a status of "invalid" as _Haringtonhippus francisci_ is now the accepted name.  Can someone with specimens and knowledge of this species confirm that's accurate and, if so, I'll amend each taxon record.

**Comment by sharpphyl** [comment]
Michelle,
Just to be more exact, I'm a retired sales and marketing person and have a few suggestions for the website (from a marketing perspective) that might be worthwhile.  If you (or a committee) have the time and inclination to discuss, let me know.

**Comment by campmlc** [comment]
Phyllis,
I think we would all be interested in your ideas. Michelle is in the field,
but if you wanted to start a document with recommendations for improvements
to the website, we could discuss at a future AWG meeting.
Thank you!

**Comment by sharpphyl** [comment]
Thanks, Mariel.  Will do.

**Comment by dustymc** [comment]
@campmlc I'm working on the relationships - Species+ is making lots of them and I'd rather not deal with a huge backlog - and http://arctos.database.museum/name/Haringtonhippus%20francisci is now as it should be.

**Comment by Jegelewicz** [comment]
@mkoo I think we should change the "Arctos Tips" under "Arctos News" on the website to "Newsletter Archive"

![image](https://user-images.githubusercontent.com/5725767/55975449-3a2d6e00-5c47-11e9-81d4-1d7062c6e631.png)

**Comment by sharpphyl** [comment]
These are my recommendations to make the website easier for potential members to navigate and to learn about Arctos.  They are in order of impact on the "customer" experience.  I've attached a Word Doc with details on each one.  There's no way one person from our membership has the time to all this, but moving this direction could be a long-term goal if AWG finds any of them to be of interest.

1.  Leverage the Home Page to communicate the key advantages of Arctos by substituting an "elevator talk" (a 30 second review of Arctos) for the duplicate links now on this page.  (The second Word doc is an image of what that might look like.)
2.  Simplify the footer to be only most important Quick Links.  
3.  Simplify the navigation around the website so there is one clear path through the website to each topic.  Currently there are many redundant paths that become confusing.
4.  Make the Menu Bar consistent in structure and content.  Either have each main menu heading be static (my preference) or active then repeat the submenus on that title page.  
5.  Miscellaneous: a series of small steps that add up to much bigger impact such as Teresa's suggestion that Arctos Tips be renamed Arctos News.   This includes sections that I've suggested we add over time to provide a more complete overview of Arctos.  Yes, I'm happy to write new sections if I know squat about the content. 

[Recommended Outline for Arctosdb.docx](https://github.com/ArctosDB/documentation-wiki/files/3074284/Recommended.Outline.for.Arctosdb.docx)

[Suggested Arctos Home Page Format.docx](https://github.com/ArctosDB/documentation-wiki/files/3074289/Suggested.Arctos.Home.Page.Format.docx)

**Comment by mkoo** [comment]
HI @sharpphyl your good suggestions are getting buried here so I am going to close this issue and create new ones for your navigation suggestions and new Home page revamp. We will have more bandwidth to take these one post-migration too (or maybe during!)
