### ISSUE TITLE
Ignore, test on How To Page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#76]
@dustymc how is this showing up? I don't see it in the How Tos in GitHub.

![image](https://user-images.githubusercontent.com/5725767/55106319-3ec52480-5094-11e9-89ea-9c1428a55312.png)

Just curious if there are other ways to add to the list.

**Comment by dustymc** [comment]
https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_how_to/markdown-test.markdown
