### ISSUE TITLE
Document fossil part cataloging

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#77]
See https://github.com/ArctosDB/arctos/issues/1976

How To: https://handbook.arctosdb.org/how_to/How-To-Catalog-Fossil-Material.html

Code: https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_how_to/How-To-Catalog-Fossil-Material.markdown

**Comment by Jegelewicz** [comment]
Please review documentation at http://handbook.arctosdb.org/how_to/How-To-Catalog-Fossil-Material.html

Let me know if anything should be changed or update or make edits yourself if you feel comfortable.

Thanks!

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I don't think we need to distinguish between appropriate part preservation attributes for body fossils vs. trace fossils because there is a lot of overlap (ex. you can have a body fossil that is a fossil cast and a trace fossil that is a fossil cast). I think we could have a list of the part preservation attributes that are appropriate for fossils.

Also, I was looking through the code table for part preservation attributes and I think carbonization got left out.

**Comment by Jegelewicz** [comment]
> Also, I was looking through the code table for part preservation attributes and I think carbonization got left out.

Added - Thanks!

**Comment by Jegelewicz** [comment]
> I don't think we need to distinguish between appropriate part preservation attributes for body fossils vs. trace fossils because there is a lot of overlap (ex. you can have a body fossil that is a fossil cast and a trace fossil that is a fossil cast). I think we could have a list of the part preservation attributes that are appropriate for fossils.

[Better now](http://handbook.arctosdb.org/how_to/How-To-Catalog-Fossil-Material.html)? Also, can you help with examples for trace fossil and coprolite? @Nicole-Ridgwell-NMMNHS

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Here are the examples you needed, I'm not sure how or if I have permissions to edit the documentation myself.

As an example, a record of a sauropod track (in this case one that is a natural mold, i.e. a convex track that represents an infilling of the original track) in Arctos would include the following:

Identification = Otozoum
part name = trace fossil
part preservation = fossil external mold

Coprolite Example
As an example, a shark coprolite catalog record in Arctos would include the following:

Identification = Chondrichthyes
part name = coprolite
part preservation = replacement

**Comment by Jegelewicz** [comment]
Thanks @Nicole-Ridgwell-NMMNHS ! See what you think of the document now.

You should be able to edit How-Tos in the documentation wiki and if you want to take stabs at it, feel free. Before that - be sure to read

https://handbook.arctosdb.org/how_to/How-to-Contribute-Content-to-Arctos-Handbook.html
and
https://handbook.arctosdb.org/how_to/How-to-Get-the-Most-from-Arctos-Github-Editing.html

(However, I always just edit right in the repository - probably not the best way, but so far it has worked for me)

**Comment by Jegelewicz** [comment]
Now that we have a Best Practice Section. I think we should move this document there with new title

Best Practice - Cataloging Fossil Material

**Comment by Jegelewicz** [comment]
Moved and closing. Anything new can come in as a new request.
