### ISSUE TITLE
gold standard taxonomy

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/documentation-wiki#79]
From https://github.com/ArctosDB/documentation-wiki/issues/72, which is getting cluttered - I nominate https://arctos.database.museum/name/Canis%20lupus as a model taxonomy page. It has

- good pictures that demonstrate how cultural collections are integrated
- relationships
- common names
- legal data

**Comment by sharpphyl** [comment]
I'll add that one in to my "how to" articles.  Thx.

**Comment by sharpphyl** [comment]
done

**Comment by sharpphyl** [comment]
done
