### ISSUE TITLE
Sharing Data and Resources

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#80]
[Sharing Data and Resources](http://handbook.arctosdb.org/documentation/sharing-data-and-resources.html) could use some beefing up with regard to operator roles and [managing an Arctos Team](http://handbook.arctosdb.org/how_to/How-to-Create-your-Arctos-Team-Users-and-Operators.html)

**Comment by Jegelewicz** [comment]
@dustymc can I edit away, or do you want me to branch and let you review first?

**Comment by dustymc** [comment]
Goferit - and events is wrong anyway, it works like locality now.

**Comment by Jegelewicz** [comment]
Need to add links to appropriate Arctos pages for

- [x] relationships
- [x] Arctos taxonomy source
- [x] Code Tables
