### ISSUE TITLE
Barcodes, Catalog Numbers and Parts 

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/documentation-wiki#81]
From @mbprondzinski 

We are struggling to settle on a numbering system for barcoding specimens. To our way of thinking, the catalog number is the most relevant number to use. The part number, which differs from the catalog number, seems redundant unless you actually have other associated parts with the specimen. Which number we use internally to barcode, be it the catalog number or the part number, should be irrelevant to our way of thinking. Even if the specimen "parts" are what link the specimen to the existing parts, the catalog number used as the barcode number is the most visible and readable to those working with the specimen and citing it. Therefore, logic tells us to go with the catalog number as the barcode number internally. How do you refute this and why? Give me a case in point.... Any input would be appreciated and thanks!

Mary Beth Prondzinski

**Comment by Jegelewicz** [comment]
This is done here - https://handbook.arctosdb.org/how_to/How-to-Start-Object-Tracking.html
