### ISSUE TITLE
documentation request: specimen detail maps

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/documentation-wiki#83]
Example: http://arctos.database.museum/guid/UCM:Fish:6064

Noteworthy stuff:

click 'more' after geography, then edit (pending https://github.com/ArctosDB/arctos/issues/2090) - the geography has a polygon

<img width="497" alt="Screen Shot 2019-05-22 at 10 49 47 AM" src="https://user-images.githubusercontent.com/5720791/58196540-5d543000-7c7f-11e9-94db-4dd75ac5a18e.png">

it's displayed on the event-map (big blue square).

<img width="329" alt="Screen Shot 2019-05-22 at 10 49 04 AM" src="https://user-images.githubusercontent.com/5720791/58196497-49103300-7c7f-11e9-8862-34c5f36b90e4.png">

locality/edit locality: the locality has a polygon.

zoom in a bit to see it...

<img width="353" alt="Screen Shot 2019-05-22 at 10 53 16 AM" src="https://user-images.githubusercontent.com/5720791/58196746-d784b480-7c7f-11e9-9740-25e9978e1a39.png">

Note the green border: the point is within the geography polygon

note the key/tools link below the map

* best option: what can we do so that doesn't need documentation?
* alternate: can someone somehow document this?

**Comment by campmlc** [comment]
This is interesting. What determines the geography polygon?
I think we need to document the difference between the locality polygon and
the error radius circle - ideally, shouldn't these be the same? It took me
a minute to notice the locality polygon within the geography polygon - some
color changes, maybe?

**Comment by dustymc** [comment]
>What determines the geography polygon?

Someone adding WKT to geography. See also https://github.com/ArctosDB/arctos/issues/1795

>shouldn't these be the same?

I think ideal would be to ditch the point-radius model altogether; those things can be represented as polygons, after all. BUT, that would make it difficult to share with anything that can't deal with polygons (so everything that's not Arctos AFAIK), be a lot more data to get to the same shape, etc. I think that's fairly unrealistic without "real" GIS capability (from which it should be trivial to generate point-radius data on demand).

In the current model they're completely independent. In this example they line up nicely and I think the WKT can be seen as a more-precise refinement. Nothing requires that, however.

For scale, there are around 500 locality polygons (mostly from some fish TCN I think) and many of them do no seem to be valid WKT. Development should probably be low-priority until we get more data, and whoever brings that data in can tell us what they want to do with it.

I can mess with the colors fairly easily, but if you zoom around enough they seem to eventually do whatever they want - Google's API is the only thing I have for this, and it's fairly 'lightweight.'

**Comment by acdoll** [comment]
I agree that keeping this in mind, but low-priority is the way to go. When we eventually have the GIS capability to calculate max distance from a point (or centriod) to the polygon border we could then ditch the point-radius model.

**Comment by Jegelewicz** [comment]
@dustymc what needs doing here?

**Comment by dustymc** [comment]
Probably nothing?
