### ISSUE TITLE
ORCID - where does it go in Arctos?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#87]
> Where in the agent record do I add the orcid?  I looked at your agent record and … I didn’t see anything obvious.  Help? - Shannen

**Comment by mkoo** [comment]
Under Address table of the Agent.cfm
The dropdown menu contains ORCID option (I used the whole URI-- I think
that's ok?!)
[image: screenshot-arctos.database.museum-2019.07.18-12-18-44.png]

**Comment by dustymc** [comment]
>used the whole URI-- I think
that's ok?!)

https://arctos.database.museum/info/ctDocumentation.cfm?table=CTADDRESS_TYPE

>The ORCID ID is a nonproprietary alphanumeric code to uniquely identify scientific and other academic authors and contributors - see https://en.wikipedia.org/wiki/ORCID. Format for Arctos is "http://orcid.org/{ORCID}" e. g. https://orcid.org/0000-0003-3985-0670
