### ISSUE TITLE
inconsistent markdown rendering

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/documentation-wiki#9]
check Mac vs PC, Chrome and FF

Right now the sidebar nav only shows up in PC (Chrome, FF) but not mac
AND **_no images_** show up in either platform or browser.

**Comment by mkoo** [comment]
I like the toc, collections as seen in your Sample File here:
https://arctosdb.github.io/documentation-wiki/documentation/sample.html

However, Mac/FF still is not behaving, look!
no sidebar nav and menus keep stacking
![screenshot-arctosdb github io 2016-08-04 22-51-41](https://cloud.githubusercontent.com/assets/2523089/17427611/cff8fc5c-5a96-11e6-8052-e9f243ed0f9f.png)

it looks good in Chrome (PC and Mac), PC/FF I think is ok too
Still no images rendered in any browser from any markdown file

**Comment by tigerhawkvok** [comment]
PC confirmed rendered fine:

![screenshot 361](https://cloud.githubusercontent.com/assets/165937/17498160/5efb0522-5d7a-11e6-9e68-9a2f8244544f.png)

![screenshot 362](https://cloud.githubusercontent.com/assets/165937/17498166/692fd748-5d7a-11e6-8936-f8deadb79811.png)

![screenshot 363](https://cloud.githubusercontent.com/assets/165937/17498170/6d98c772-5d7a-11e6-9c72-f6af6b540c52.png)

OSX tests inbound

**Comment by tigerhawkvok** [comment]
Mac

![screenshot 2016-08-08 15 18 05](https://cloud.githubusercontent.com/assets/165937/17498393/fc9133e6-5d7b-11e6-9c58-b70b079242c5.png)

![screenshot 2016-08-08 15 25 16](https://cloud.githubusercontent.com/assets/165937/17498459/6894bf90-5d7c-11e6-818c-e0d513c55b7e.png)

Seems fine here. Does it replicate still for you?

**Comment by mkoo** [comment]
hang on-- I still can replicate in Mac/FF
Also see the menu bar, stacked!
And I added in _resources this weekend which is not rendered as a menu
item.

sigh, I will go through extensions next (but not in next hour)...

**Comment by tigerhawkvok** [comment]
Yeah we should resolve what's causing the different rendering, even within macs ..

**Comment by mkoo** [comment]
ok, I have an answer: Mac/FF plugin Adblocker Plus rendered the menu and
sidebar nav null. Everything looks great if disabled on page.

**Comment by tigerhawkvok** [comment]
Images are working, too:

![image](https://cloud.githubusercontent.com/assets/165937/17531211/c6dbf920-5e2f-11e6-968d-1f657dc89b15.png)

https://arctosdb.github.io/documentation-wiki/documentation/sample.html

Are the correct paths being used? If it's not pointing to the `/raw/` github folder, it's trying to use an html file as an image ... eg, the correct syntax would be

```
![](https://raw.githubusercontent.com/ArctosDB/documentation-wiki/master/tutorial_images/edit_parts.jpg)
```
