### ISSUE TITLE
move georeferencing to geolocate

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/documentation-wiki#96]
Google's /geocode/ API has changed and is now even worse for the kind of data we normally have. Geolocate seems to do much better. Recommend we:

- feed text data to geolocate
- use the result for s$coordinates
- feed coordinate and s$coordinates to google, merge the results for s$geography

**Comment by Jegelewicz** [comment]
@dusty Are these examples and the proposed solutions still correct?

-   There are some situations in which no Specific Locality is given, or no
    Specific Locality would be appropriate. For example, collecting events on the
    high seas which are specified by geographic latitude and longitude.

    -   **Example:** North Pacific Ocean, 45 52′ 24″ N, 165 21′ 48″ W

    Or a collecting event on an island that is specified in the
    Higher Geography.

    -   **Example:** USA, Alaska, Petersburg quad, Thorne Island

    In these examples, as well as in records for which appropriate data
    are missing, the correct value for Specific Locality is, "**No
    specific locality recorded.**"

**Comment by dustymc** [comment]
That's not me, but...

The examples are horrid, the latter especially. Remove all examples??

Google is no longer used at all and should be removed if it's still hanging around.

Specloc as machine-readable verbatim locality is more important than ever (and https://github.com/ArctosDB/documentation-wiki/issues/291 is relevant to that, but maybe not distilled enough for documentation yet).

There will be times when there's nothing to say in specific locality for various reasons, and ``No
specific locality recorded.`` is the way to do so (for now?).

[North Pacific Ocean](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1147) is assertable geography, if that matters.

[no specific higher geography](https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=10016350)   is a sorta-new idea and could maybe use elaboration.

Given good shape-data (polygon or coordinates+error), any correct geography is about as good as anything, since all relevant geographies will be rounded up and cached (albeit eventually because https://github.com/ArctosDB/internal/issues/222). Whatever the geography given for the cooordinate example, it will end up findable by North Pacific Ocean. There's little functional difference between asserting  North Pacific Ocean or no specific higher geography for the discovery of records at that point. (Asserting "Kansas" would not make it less discoverable, but would confuse anyone who found it. Asserting North Pacific Ocean might somehow lead to more believability, but I think that's really infringing on verbatim locality's job.)

Sorta-almost opposite that, given good geography and specific locality, Arctos will figure out the shape-data (and then use that to figure out appropriate geography, which might be a bit circular).

I wonder if the documentation couldn't be simplified in recognition of Arctos' spatial and webservice functionality? I think for most cases spending whatever time's spent trying to figure out geography would be better spent on writing really good specific locality data, or better yet creating a really good georeference. That's probably especially true on the end of the spectrum opposite those coordinates out in the middle of the ocean: a really good georeference that spans three counties in two states is MORE USEFUL in every way when the geography assertion isn't to a single one of those counties (in which case I'll never be sure if I should ignore the stuff in the other two, or if they just felt compelled to pick some county-level geography because that was seen as a best practice when geography was strings in spreadsheet-like structures). In other words, the georeference (plus maybe country-level geography or even 'no specific higher geography') is implicitly a geography assertion of the two states and the three counties; the record is findable by any of that.

Yea, I wandered off a bit, hope it's useful anyway....

**Comment by Jegelewicz** [comment]
> Yea, I wandered off a bit

So have I - I've been editing the Locality documentation because https://github.com/ArctosDB/documentation-wiki/issues/96#issuecomment-494894953

But it looks like it really could use more and I think a lot of the examples were put there by @mkoo ? Many of them seem like good ideas (Best Practices?) that probably nobody ever sees....and I think this points to the need for deciding how documentation needs to be set up. See https://github.com/ArctosDB/documentation-wiki/issues/251

**Comment by Jegelewicz** [comment]
> Google is no longer used at all and should be removed if it's still hanging around.

Even for maps? The only references I find in documentation relate to using Google maps

![image](https://user-images.githubusercontent.com/5725767/212780753-2919cf73-79ef-4639-88b7-2ce270be68a6.png)
in https://handbook.arctosdb.org/how_to/How-to-Search-for-Specimens.html 

and to using Google to help figure stuff out

![image](https://user-images.githubusercontent.com/5725767/212780816-72e326ba-4b66-44d1-9ca1-3fc54d005781.png)
in https://handbook.arctosdb.org/documentation/higher-geography.html

![image](https://user-images.githubusercontent.com/5725767/212780982-425d390d-f0b0-44a0-889b-19f18916273e.png)
https://handbook.arctosdb.org/documentation/locality.html

![image](https://user-images.githubusercontent.com/5725767/212781147-389b328c-6fc1-4567-828c-326a8c0adc98.png)
https://handbook.arctosdb.org/how_to/How-to-Enter-Data-for-a-Single-Record.html

and sometimes, I have no idea why

![image](https://user-images.githubusercontent.com/5725767/212781104-89e1c9f9-81c2-45c1-a4b3-c4aafebadc5d.png)
https://handbook.arctosdb.org/how_to/How-to-Enter-Data-for-a-Single-Record.html

So I think we can close this?

**Comment by dustymc** [comment]
>Even for maps?

Speaking of wildfires...

https://github.com/ArctosDB/internal/issues/44

We are using Google for maps, at least until they pull the rug out from under us, again.
